#!/bin/csh
#########################################
set userv = `uname -s`
echo $userv
if ("$userv" == "SunOS") then
alias awk nawk
else if ("$userv" == "Linux") then
alias awk gawk
else
alias awk awk95
endif
####define  genesis path


set custp = `cat "$GENESIS_DIR/fw/jobs/$JOB/user/custp"`
if ($custp == 0054 || $custp == 0771 || $custp == 0322) then
notepad.exe "$GENESIS_DIR/fw/lib/forms/sl_opgerber/def/cb/054.txt"
exit
endif

###################################–«ø’Œﬁœﬁ
set liu = 1
set cai = 2
set lin = `echo "scale=0;$liu + $cai"|bc`
echo "$liu $cai $lin"
COM read_form,job=$JOB,form=sl_opgerber,elem=path
set pathxx = "$COMANS"





#########################################
set gui_path = ()
if ("$userv" == "SunOS") then
  set gui_path = /genesis/e90/all/gui
  set scp_path = /genesis/sys/scripts
  set gui_inpath = /tmp/gui_in.$$
  set gui_outpath = /tmp/gui_out.$$
else if ("$userv" == "Linux") then
 set gui_path = /genesis/e90/all/gui
 set scp_path = /genesis/sys/scripts
 set gui_inpath = /tmp/gui_in.$$
 set gui_outpath = /tmp/gui_out.$$
else
set disk = (c d e f g h)
  foreach disk($disk)
   if (-e ${disk}:/genesis) then
       set pan = $disk
       set scp_path = ${disk}:/genesis/sys/scripts
       set gui_inpath = ${disk}:/tmp/gui_in.$$
       set gui_outpath = ${disk}:/tmp/gui_out.$$
       if (-e ${disk}:/genesis/e90/all/gui.exe) then
        set gui_path = "${disk}:/genesis/e90/all/gui"
       else if(-e ${disk}:/genesis/e91/all/gui.exe) then
        set gui_path = "${disk}:/genesis/e90/all/gui"
       else if(-e ${disk}:/genesis/e92/all/gui.exe) then
        set gui_path = "${disk}:/genesis/e92/all/gui"
       endif
    endif
  end 
endif
#######################################
set date = `date +%y`
#source $scp_path/include_me
COM read_form,job=$JOB,form=sl_opgerber,elem=display
set display = "$COMANS"
echo "$display"
COM read_form,job=$JOB,form=sl_opgerber,elem=job
set jobname = "$COMANS"
COM read_form,job=$JOB,form=sl_opgerber,elem=step,opt_name=yes
set step = "$COMANS"
echo $step
COM read_form,job=$JOB,form=sl_opgerber,elem=path
set pathxx = "$COMANS"
set pathxx = "$pathxx/sp"

COM open_entity,job=$JOB,type=step,name=$step,iconic=no
set group_number=$COMANS
AUX set_group,group=$group_number
DO_INFO -t layer -e $JOB/$step/gtl -d exists
if ($gEXISTS == yes) then
COM display_layer,name=gtl,display=yes,number=1
COM work_layer,name=gtl
COM get_work_layer
COM disp_on
COM origin_on
COM filter_set,filter_name=popup,update_popup=no,include_syms=r1128.877
COM filter_area_strt
COM filter_area_end,layer=,filter_name=popup,operation=select,\
area_type=none,inside_area=no,intersect_area=no,lines_only=no,\
ovals_only=no,min_len=0,max_len=0,min_angle=0,max_angle=0
COM get_select_count
set select = $COMANS
if ($select < 3) then
COM filter_reset,filter_name=popup
set gui_in = $TMP/gui_in.$$
set gui_out = $TMP/gui_out.$$
echo "WIN 200 200" > $gui_in
echo "LABEL @$GENESIS_DIR/fw/lib/forms/sl_opgerber/def/pixmaps/123.xpm" >> $gui_in
$GENESIS_EDIR/all/gui $gui_in > $gui_out
COM display_layer,name=gtl,display=no,number=1
exit;
endif
COM display_layer,name=gtl,display=no,number=1
endif


DO_INFO -t layer -e $JOB/$step/gbl -d exists
if ($gEXISTS == yes) then
COM display_layer,name=gbl,display=yes,number=1
COM work_layer,name=gbl
COM get_work_layer
COM disp_on
COM origin_on
COM filter_set,filter_name=popup,update_popup=no,include_syms=r1128.877
COM filter_area_strt
COM filter_area_end,layer=,filter_name=popup,operation=select,\
area_type=none,inside_area=no,intersect_area=no,lines_only=no,\
ovals_only=no,min_len=0,max_len=0,min_angle=0,max_angle=0
COM get_select_count
set select = $COMANS
if ($select < 3) then
COM filter_reset,filter_name=popup
set gui_in = $TMP/gui_in.$$
set gui_out = $TMP/gui_out.$$
echo "WIN 200 200" > $gui_in
echo "LABEL @$GENESIS_DIR/fw/lib/forms/sl_opgerber/def/pixmaps/123.xpm" >> $gui_in
$GENESIS_EDIR/all/gui $gui_in > $gui_out
COM display_layer,name=gbl,display=no,number=1
exit;
endif
COM display_layer,name=gbl,display=no,number=1
endif



COM output_layer_reset

if ($step == panela || $step == pa) then
set fix = "${jobname}a."
else if ($step == panelb || $step == pb) then
set fix = "${jobname}b."
else
set fix = "${jobname}."
endif


set tmp = 1
set display = ($display)
while ($tmp <=  $#display)
set layername = `echo "$display[$tmp]" |cut -c1-3` 
if ($layername == gbl) then
COM output_layer_reset
COM output_layer_set,layer=$display[$tmp],angle=270,mirror=yes,x_scale=1,y_scale=1,\
comp=0,polarity=positive,setupfile=,setupfiletmp=,line_units=inch,\
gscl_file=
COM output,job=$jobname,step=$step,format=Gerber274x,dir_path=$pathxx,\
prefix=${fix},suffix=,break_sr=yes,break_symbols=yes,break_arc=yes,\
scale_mode=all,surface_mode=contour,min_brush=1,units=inch,coordinates=absolute,\
zeroes=leading,nf1=2,nf2=5,x_anchor=0,y_anchor=0,wheel=,x_offset=0,\
y_offset=0,line_units=inch,override_online=yes,film_size_cross_scan=0,\
film_size_along_scan=0,ds_model=RG6500
COM disp_on
COM origin_on

#####################################
else if ($layername == gtl) then
#################
  COM output_layer_reset
  COM output_layer_set,layer=$display[$tmp],angle=270,mirror=no,x_scale=1,y_scale=1,\
  comp=0,polarity=positive,setupfile=,setupfiletmp=,line_units=inch,\
  gscl_file=
  COM output,job=$jobname,step=$step,format=Gerber274x,dir_path=$pathxx,\
  prefix=${fix},suffix=,break_sr=yes,break_symbols=yes,break_arc=yes,\
  scale_mode=all,surface_mode=contour,min_brush=1,units=inch,coordinates=absolute,\
  zeroes=leading,nf1=2,nf2=5,x_anchor=0,y_anchor=0,wheel=,x_offset=0,\
  y_offset=0,line_units=inch,override_online=yes,film_size_cross_scan=0,\
  film_size_along_scan=0,ds_model=RG6500
   COM disp_on
   COM origin_on
else if ($layername == gbo) then
    COM output_layer_reset
    COM output_layer_set,layer=$display[$tmp],angle=270,mirror=yes,x_scale=1,y_scale=1,\
    comp=0,polarity=positive,setupfile=,setupfiletmp=,line_units=inch,\
    gscl_file=
   COM output,job=$jobname,step=$step,format=Gerber274x,dir_path=$pathxx,\
   prefix=${fix},suffix=,break_sr=yes,break_symbols=yes,break_arc=yes,\
   scale_mode=all,surface_mode=fill,min_brush=1,units=inch,coordinates=absolute,\
    zeroes=leading,nf1=2,nf2=5,x_anchor=0,y_anchor=0,wheel=,x_offset=0,\
    y_offset=0,line_units=inch,override_online=yes,film_size_cross_scan=0,\
   film_size_along_scan=0,ds_model=RG6500
   COM disp_on
   COM origin_on
 else if ($layername == gto) then
    COM output_layer_reset
    COM output_layer_set,layer=$display[$tmp],angle=270,mirror=no,x_scale=1,y_scale=1,\
    comp=0,polarity=positive,setupfile=,setupfiletmp=,line_units=inch,\
    gscl_file=
    COM output,job=$jobname,step=$step,format=Gerber274x,dir_path=$pathxx,\
    prefix=${fix},suffix=,break_sr=yes,break_symbols=yes,break_arc=yes,\
    scale_mode=all,surface_mode=fill,min_brush=1,units=inch,coordinates=absolute,\
    zeroes=leading,nf1=2,nf2=5,x_anchor=0,y_anchor=0,wheel=,x_offset=0,\
    y_offset=0,line_units=inch,override_online=yes,film_size_cross_scan=0,\
    film_size_along_scan=0,ds_model=RG6500
    COM disp_on
    COM origin_on
    COM output_layer_set,layer=$display[$tmp],angle=270,mirror=no,x_scale=1,y_scale=1,\
        comp=0,polarity=positive,setupfile=,setupfiletmp=,line_units=inch,\
        gscl_file=
endif


@ tmp++
end





test -e "$pathxx/${fix}gtl"
if ($? == 0) then
set value = `sed -n '/C,0.044444/'p "$pathxx/${fix}gtl"`
set valuel = `expr length "$value"`
set valuel1 = `echo "scale=0;$valuel - 2"|bc`
set value1 = `echo "$value" |cut -c2-$valuel1`
echo "$value1"

set valuel2 = `echo "scale=0;$valuel - 11"|bc`
set valued = `echo "$value" |cut -c2-$valuel2`
set valued = `echo "$valued" | sed 's/[a-zA-Z]//g'`
set valued = "G54D$valued"
echo "$valued"
sed s/$value1/ADD999C,0.044444/ "$pathxx/${fix}gtl" > "$pathxx/${fix}gtlnew"
sed s/$valued/"G54D999"/ "$pathxx/${fix}gtlnew" > "$pathxx/${fix}gtl"
rm -rf "$pathxx/${fix}gtlnew"

endif


test -e "$pathxx/${fix}gbl"
if ($? == 0) then
set value = `sed -n '/C,0.044444/'p "$pathxx/${fix}gbl"`
set valuel = `expr length "$value"`
set valuel1 = `echo "scale=0;$valuel - 2"|bc`
set value1 = `echo "$value" |cut -c2-$valuel1`
echo "$value1"
set valuel2 = `echo "scale=0;$valuel - 11"|bc`
set valued = `echo "$value" |cut -c2-$valuel2`
set valued = `echo "$valued" | sed 's/[a-zA-Z]//g'`
set valued = "G54D$valued"
echo "$valued"



sed s/$value1/ADD999C,0.044444/ "$pathxx/${fix}gbl" > "$pathxx/${fix}gblnew"
sed s/$valued/"G54D999"/ "$pathxx/${fix}gblnew" > "$pathxx/${fix}gbl"
rm -rf "$pathxx/${fix}gblnew"

endif

echo "dd"