#!/bin/csh
#########################################
set userv = `uname -s`
echo $userv
if ("$userv" == "SunOS") then
alias awk nawk
else if ("$userv" == "Linux") then
alias awk gawk
else
alias awk awk95
endif
####define  genesis path

DO_INFO -t step -e $job/edit -d exists
if ($gEXISTS == yes) then
###################################################
DO_INFO -t step -e $job/net -d exists
if ($gEXISTS == yes) then
set job = $JOB
COM netlist_page_open,set=yes,job1=$job,job2=$job
COM netlist_recalc,job=$job,step=net,type=cur,display=top
COM netlist_ref_update,job=$job,step=net,source=cur,reduce=yes
COM netlist_recalc,job=$job,step=edit,type=cur,display=bottom
COM netlist_recalc,job=$job,step=net,type=ref,display=top
COM netlist_recalc,job=$job,step=edit,type=cur,display=bottom
COM netlist_compare,job1=$job,step1=net,type1=ref,job2=$job,step2=edit,type2=cur,display=yes
else
set job = $JOB
DO_INFO -t step -e $job/orig -d exists
if ($gEXISTS == yes) then
COM netlist_page_open,set=yes,job1=$job,job2=$job
COM netlist_recalc,job=$job,step=orig,type=cur,display=top
COM netlist_ref_update,job=$job,step=orig,source=cur,reduce=yes
COM netlist_recalc,job=$job,step=edit,type=cur,display=bottom
COM netlist_recalc,job=$job,step=orig,type=ref,display=top
COM netlist_recalc,job=$job,step=edit,type=cur,display=bottom
COM netlist_compare,job1=$job,step1=orig,type1=ref,job2=$job,step2=edit,type2=cur,display=yes
endif
endif
####################################################
endif
PAUSE r netlist is ok?
###################################–«ø’Œﬁœﬁ
set liu = 1
set cai = 2
set lin = `echo "scale=0;$liu + $cai"|bc`
echo "$liu $cai $lin"
COM read_form,job=$JOB,form=sl_opgerber,elem=path
set pathxx = "$COMANS"
#########################################
set gui_path = ()
if ("$userv" == "SunOS") then
  set gui_path = /genesis/e90/all/gui
  set scp_path = /genesis/sys/scripts
  set gui_inpath = /tmp/gui_in.$$
  set gui_outpath = /tmp/gui_out.$$
else if ("$userv" == "Linux") then
 set gui_path = /genesis/e90/all/gui
 set scp_path = /genesis/sys/scripts
 set gui_inpath = /tmp/gui_in.$$
 set gui_outpath = /tmp/gui_out.$$
else
set disk = (c d e f g h)
  foreach disk($disk)
   if (-e ${disk}:/genesis) then
       set pan = $disk
       set scp_path = ${disk}:/genesis/sys/scripts
       set gui_inpath = ${disk}:/tmp/gui_in.$$
       set gui_outpath = ${disk}:/tmp/gui_out.$$
       if (-e ${disk}:/genesis/e90/all/gui.exe) then
        set gui_path = "${disk}:/genesis/e90/all/gui"
       else if(-e ${disk}:/genesis/e91/all/gui.exe) then
        set gui_path = "${disk}:/genesis/e90/all/gui"
       else if(-e ${disk}:/genesis/e92/all/gui.exe) then
        set gui_path = "${disk}:/genesis/e92/all/gui"
       endif
    endif
  end 
endif
#######################################
set date = `date +%y`
#source $scp_path/include_me
COM read_form,job=$JOB,form=sl_opgerber,elem=display
set display = "$COMANS"
echo "$display"
COM read_form,job=$JOB,form=sl_opgerber,elem=job
set jobname = "$COMANS"
COM read_form,job=$JOB,form=sl_opgerber,elem=step,opt_name=yes
set step = "$COMANS"
echo $step
COM read_form,job=$JOB,form=sl_opgerber,elem=path
set pathxx = "$COMANS"
COM output_layer_reset
set tmp = 1
set display = ($display)
set ccdmake = 0
while ($tmp <=  $#display) 
if ($display[$tmp] == gtl || $display[$tmp] == gbl) then
set ccdmake = 1
endif
@ tmp++
end
set first = `echo "$JOB"|cut -c1`
if ($ccdmake == 1 && $first != s && $first != u && $first != t) then
set gui_in = $TMP/gui_in.$$
set gui_out = $TMP/gui_out.$$
echo "WIN 200 200" > $gui_in
echo "RADIO ccdo '"@$GENESIS_DIR/fw/lib/forms/sl_opgerber/def/pixmaps/ccd.xpm"' H 2 88000 " >> $gui_in
echo "No" >> $gui_in 
echo "Yes   " >> $gui_in 
echo "END" >> $gui_in 
$GENESIS_EDIR/all/gui $gui_in > $gui_out
source $gui_out
echo "$ccdo fffffffffffff"


COM open_entity,job=$JOB,type=step,name=$step,iconic=no
set group_number=$COMANS
AUX set_group,group=$group_number
DO_INFO -t layer -e $JOB/$step/gtl -d exists
if ($gEXISTS == yes) then
COM display_layer,name=gtl,display=yes,number=1
COM work_layer,name=gtl
COM get_work_layer
COM disp_on
COM origin_on
COM filter_set,filter_name=popup,update_popup=no,include_syms=r254
COM filter_area_strt
COM filter_area_end,layer=,filter_name=popup,operation=select,\
area_type=none,inside_area=no,intersect_area=no,lines_only=no,\
ovals_only=no,min_len=0,max_len=0,min_angle=0,max_angle=0
COM get_select_count
set cselect = $COMANS
endif

DO_INFO -t layer -e $JOB/$step/gbl -d exists
if ($gEXISTS == yes) then
COM display_layer,name=gbl,display=yes,number=1
COM work_layer,name=gbl
COM get_work_layer
COM disp_on
COM origin_on
COM filter_set,filter_name=popup,update_popup=no,include_syms=r254
COM filter_area_strt
COM filter_area_end,layer=,filter_name=popup,operation=select,\
area_type=none,inside_area=no,intersect_area=no,lines_only=no,\
ovals_only=no,min_len=0,max_len=0,min_angle=0,max_angle=0
COM get_select_count
set sselect = $COMANS
endif

if ($ccdo == 2) then
if ($cselect != 4 && $sselect != 4) then
set gui_in = $TMP/gui_in.$$
set gui_out = $TMP/gui_out.$$
echo "WIN 200 200" > $gui_in
echo "LABEL @$GENESIS_DIR/fw/lib/forms/sl_opgerber/def/pixmaps/noccd.xpm" >> $gui_in
$GENESIS_EDIR/all/gui $gui_in > $gui_out
exit
endif
else
if ($cselect != 0 || $sselect != 0) then
set gui_in = $TMP/gui_in.$$
set gui_out = $TMP/gui_out.$$
echo "WIN 200 200" > $gui_in
echo "LABEL @$GENESIS_DIR/fw/lib/forms/sl_opgerber/def/pixmaps/ccdd.xpm">> $gui_in
$GENESIS_EDIR/all/gui $gui_in > $gui_out
exit
endif

endif

endif

set tmp = 1
#############################################################
while ($tmp <=  $#display) 
COM output_layer_set,layer=$display[$tmp],angle=0,mirror=no,x_scale=1,y_scale=1,\
comp=0,polarity=positive,setupfile=,setupfiletmp=,line_units=inch,\
gscl_file=
@ tmp++
end



if ($step == panela || $step == pa) then
set fix = "${jobname}a."
else if ($step == panelb || $step == pb) then
set fix = "${jobname}b."
else
set fix = "${jobname}."
endif

COM output,job=$jobname,step=$step,format=Gerber274x,dir_path=$pathxx,\
prefix=${fix},suffix=,break_sr=yes,break_symbols=yes,break_arc=yes,\
scale_mode=all,surface_mode=fill,min_brush=1,units=inch,coordinates=absolute,\
zeroes=leading,nf1=2,nf2=5,x_anchor=0,y_anchor=0,wheel=,x_offset=0,\
y_offset=0,line_units=inch,override_online=yes,film_size_cross_scan=0,\
film_size_along_scan=0,ds_model=RG6500

COM disp_on
COM origin_on

notepad.exe "$GENESIS_DIR/fw/lib/forms/sl_opgerber/def/cb/note.txt"

echo "dd"