# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui.ui'
#
# Created: Mon Nov 20 19:43:40 2023
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(512, 622)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setStyleSheet(_fromUtf8(""))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sh_log = QtGui.QLabel(self.frame_3)
        self.sh_log.setMinimumSize(QtCore.QSize(150, 0))
        self.sh_log.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sh_log.setFrameShadow(QtGui.QFrame.Sunken)
        self.sh_log.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sh_log.setObjectName(_fromUtf8("sh_log"))
        self.horizontalLayout.addWidget(self.sh_log)
        self.line_3 = QtGui.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.label_3 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 492, 492))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.pushButton_creat_pnl = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_creat_pnl.setMinimumSize(QtCore.QSize(25, 0))
        self.pushButton_creat_pnl.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_creat_pnl.setText(_fromUtf8(""))
        self.pushButton_creat_pnl.setObjectName(_fromUtf8("pushButton_creat_pnl"))
        self.horizontalLayout_33.addWidget(self.pushButton_creat_pnl)
        self.laber_creat_pnl = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.laber_creat_pnl.setFont(font)
        self.laber_creat_pnl.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);"))
        self.laber_creat_pnl.setFrameShape(QtGui.QFrame.NoFrame)
        self.laber_creat_pnl.setFrameShadow(QtGui.QFrame.Plain)
        self.laber_creat_pnl.setObjectName(_fromUtf8("laber_creat_pnl"))
        self.horizontalLayout_33.addWidget(self.laber_creat_pnl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_33)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fram_desiger = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.fram_desiger.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fram_desiger.setFrameShadow(QtGui.QFrame.Sunken)
        self.fram_desiger.setObjectName(_fromUtf8("fram_desiger"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.fram_desiger)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.fram_11 = QtGui.QFrame(self.fram_desiger)
        self.fram_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fram_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.fram_11.setObjectName(_fromUtf8("fram_11"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.fram_11)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.sET_XLabel = QtGui.QLabel(self.fram_11)
        self.sET_XLabel.setObjectName(_fromUtf8("sET_XLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sET_XLabel)
        self.sET_XLineEdit = QtGui.QLineEdit(self.fram_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sET_XLineEdit.setFont(font)
        self.sET_XLineEdit.setReadOnly(True)
        self.sET_XLineEdit.setObjectName(_fromUtf8("sET_XLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sET_XLineEdit)
        self.sET_YLabel = QtGui.QLabel(self.fram_11)
        self.sET_YLabel.setObjectName(_fromUtf8("sET_YLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.sET_YLabel)
        self.sET_YLineEdit = QtGui.QLineEdit(self.fram_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sET_YLineEdit.setFont(font)
        self.sET_YLineEdit.setReadOnly(True)
        self.sET_YLineEdit.setObjectName(_fromUtf8("sET_YLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sET_YLineEdit)
        self.pCSSETLabel = QtGui.QLabel(self.fram_11)
        self.pCSSETLabel.setObjectName(_fromUtf8("pCSSETLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.pCSSETLabel)
        self.pCSSETLineEdit = QtGui.QLineEdit(self.fram_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pCSSETLineEdit.setFont(font)
        self.pCSSETLineEdit.setReadOnly(True)
        self.pCSSETLineEdit.setObjectName(_fromUtf8("pCSSETLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.pCSSETLineEdit)
        self.horizontalLayout_5.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.sET_XLabel_2 = QtGui.QLabel(self.fram_11)
        self.sET_XLabel_2.setObjectName(_fromUtf8("sET_XLabel_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.sET_XLabel_2)
        self.sET_XLineEdit_2 = QtGui.QLineEdit(self.fram_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sET_XLineEdit_2.setFont(font)
        self.sET_XLineEdit_2.setReadOnly(True)
        self.sET_XLineEdit_2.setObjectName(_fromUtf8("sET_XLineEdit_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.sET_XLineEdit_2)
        self.sET_YLabel_2 = QtGui.QLabel(self.fram_11)
        self.sET_YLabel_2.setObjectName(_fromUtf8("sET_YLabel_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.sET_YLabel_2)
        self.sET_YLineEdit_2 = QtGui.QLineEdit(self.fram_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sET_YLineEdit_2.setFont(font)
        self.sET_YLineEdit_2.setReadOnly(True)
        self.sET_YLineEdit_2.setObjectName(_fromUtf8("sET_YLineEdit_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.sET_YLineEdit_2)
        self.pCSSETLabel_2 = QtGui.QLabel(self.fram_11)
        self.pCSSETLabel_2.setObjectName(_fromUtf8("pCSSETLabel_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.pCSSETLabel_2)
        self.pCSSETLineEdit_2 = QtGui.QLineEdit(self.fram_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pCSSETLineEdit_2.setFont(font)
        self.pCSSETLineEdit_2.setReadOnly(True)
        self.pCSSETLineEdit_2.setObjectName(_fromUtf8("pCSSETLineEdit_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.pCSSETLineEdit_2)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.fram_11)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_desiger = QtGui.QPushButton(self.fram_desiger)
        self.pushButton_desiger.setObjectName(_fromUtf8("pushButton_desiger"))
        self.horizontalLayout_6.addWidget(self.pushButton_desiger)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.fram_desiger)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.pushButton_copper = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_copper.setMinimumSize(QtCore.QSize(25, 0))
        self.pushButton_copper.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_copper.setText(_fromUtf8(""))
        self.pushButton_copper.setObjectName(_fromUtf8("pushButton_copper"))
        self.horizontalLayout_32.addWidget(self.pushButton_copper)
        self.laber_re_copper = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.laber_re_copper.setFont(font)
        self.laber_re_copper.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);"))
        self.laber_re_copper.setFrameShape(QtGui.QFrame.NoFrame)
        self.laber_re_copper.setFrameShadow(QtGui.QFrame.Plain)
        self.laber_re_copper.setObjectName(_fromUtf8("laber_re_copper"))
        self.horizontalLayout_32.addWidget(self.laber_re_copper)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.frame_copper = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_copper.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_copper.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_copper.setLineWidth(5)
        self.frame_copper.setObjectName(_fromUtf8("frame_copper"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_copper)
        self.verticalLayout.setContentsMargins(-1, 2, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(15, 5, -1, 5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_set_size = QtGui.QPushButton(self.frame_copper)
        self.pushButton_set_size.setMinimumSize(QtCore.QSize(25, 0))
        self.pushButton_set_size.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_set_size.setText(_fromUtf8(""))
        self.pushButton_set_size.setObjectName(_fromUtf8("pushButton_set_size"))
        self.horizontalLayout_2.addWidget(self.pushButton_set_size)
        self.label = QtGui.QLabel(self.frame_copper)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_copper_type_set = QtGui.QComboBox(self.frame_copper)
        self.comboBox_copper_type_set.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_copper_type_set.setFont(font)
        self.comboBox_copper_type_set.setObjectName(_fromUtf8("comboBox_copper_type_set"))
        self.horizontalLayout_2.addWidget(self.comboBox_copper_type_set)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.fram_select_layer = QtGui.QFrame(self.frame_copper)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fram_select_layer.sizePolicy().hasHeightForWidth())
        self.fram_select_layer.setSizePolicy(sizePolicy)
        self.fram_select_layer.setFrameShape(QtGui.QFrame.NoFrame)
        self.fram_select_layer.setFrameShadow(QtGui.QFrame.Sunken)
        self.fram_select_layer.setObjectName(_fromUtf8("fram_select_layer"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.fram_select_layer)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(1)
        self.horizontalLayout_23.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_28 = QtGui.QLabel(self.fram_select_layer)
        self.label_28.setMinimumSize(QtCore.QSize(60, 20))
        self.label_28.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);"))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_23.addWidget(self.label_28)
        self.label_31 = QtGui.QLabel(self.fram_select_layer)
        self.label_31.setMinimumSize(QtCore.QSize(80, 20))
        self.label_31.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet(_fromUtf8("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);"))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_23.addWidget(self.label_31)
        self.label_35 = QtGui.QLabel(self.fram_select_layer)
        self.label_35.setMinimumSize(QtCore.QSize(80, 20))
        self.label_35.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet(_fromUtf8("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);"))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_23.addWidget(self.label_35)
        self.label_32 = QtGui.QLabel(self.fram_select_layer)
        self.label_32.setMinimumSize(QtCore.QSize(80, 20))
        self.label_32.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet(_fromUtf8("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);"))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_23.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.fram_select_layer)
        self.label_33.setMinimumSize(QtCore.QSize(60, 20))
        self.label_33.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet(_fromUtf8("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);"))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_23.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.fram_select_layer)
        self.label_34.setMinimumSize(QtCore.QSize(0, 20))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet(_fromUtf8("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);"))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_23.addWidget(self.label_34)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.table_copper = QtGui.QTableWidget(self.fram_select_layer)
        self.table_copper.setMinimumSize(QtCore.QSize(0, 0))
        self.table_copper.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_copper.setStyleSheet(_fromUtf8("background-color: rgb(248, 248, 248);"))
        self.table_copper.setFrameShape(QtGui.QFrame.StyledPanel)
        self.table_copper.setFrameShadow(QtGui.QFrame.Sunken)
        self.table_copper.setObjectName(_fromUtf8("table_copper"))
        self.table_copper.setColumnCount(0)
        self.table_copper.setRowCount(0)
        self.table_copper.horizontalHeader().setStretchLastSection(True)
        self.table_copper.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.table_copper)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_apply = QtGui.QPushButton(self.fram_select_layer)
        self.pushButton_apply.setObjectName(_fromUtf8("pushButton_apply"))
        self.horizontalLayout_3.addWidget(self.pushButton_apply)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout.addWidget(self.fram_select_layer)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.frame_copper)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_back = QtGui.QPushButton(self.centralwidget)
        self.pushButton_back.setObjectName(_fromUtf8("pushButton_back"))
        self.horizontalLayout_4.addWidget(self.pushButton_back)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pushButton_updata = QtGui.QPushButton(self.centralwidget)
        self.pushButton_updata.setObjectName(_fromUtf8("pushButton_updata"))
        self.horizontalLayout_4.addWidget(self.pushButton_updata)
        self.pushButton_exit = QtGui.QPushButton(self.centralwidget)
        self.pushButton_exit.setObjectName(_fromUtf8("pushButton_exit"))
        self.horizontalLayout_4.addWidget(self.pushButton_exit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 512, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.sh_log.setText(_translate("MainWindow", "img", None))
        self.label_3.setText(_translate("MainWindow", "计算内层残铜率", None))
        self.laber_creat_pnl.setText(_translate("MainWindow", "拼板参数", None))
        self.sET_XLabel.setText(_translate("MainWindow", "SET_X", None))
        self.sET_YLabel.setText(_translate("MainWindow", "SET_Y", None))
        self.pCSSETLabel.setText(_translate("MainWindow", "PCS/SET", None))
        self.sET_XLabel_2.setText(_translate("MainWindow", "PNL_X", None))
        self.sET_YLabel_2.setText(_translate("MainWindow", "PNL_Y", None))
        self.pCSSETLabel_2.setText(_translate("MainWindow", "SET/PNL", None))
        self.pushButton_desiger.setText(_translate("MainWindow", "执行拼版", None))
        self.laber_re_copper.setText(_translate("MainWindow", "铺铜参数", None))
        self.pushButton_set_size.setToolTip(_translate("MainWindow", "设置大小间距", None))
        self.label.setText(_translate("MainWindow", "SET铺铜:", None))
        self.label_28.setText(_translate("MainWindow", "层别", None))
        self.label_31.setText(_translate("MainWindow", "极性", None))
        self.label_35.setText(_translate("MainWindow", "SET铺铜", None))
        self.label_32.setText(_translate("MainWindow", "PNL铺铜", None))
        self.label_33.setText(_translate("MainWindow", "残铜率", None))
        self.label_34.setText(_translate("MainWindow", "备注", None))
        self.pushButton_apply.setText(_translate("MainWindow", "执行铺铜", None))
        self.pushButton_back.setText(_translate("MainWindow", "查看Genesis", None))
        self.pushButton_updata.setToolTip(_translate("MainWindow", "计算铜面积并上传", None))
        self.pushButton_updata.setText(_translate("MainWindow", "上传铜面积", None))
        self.pushButton_exit.setText(_translate("MainWindow", "退出", None))
        self.menu.setTitle(_translate("MainWindow", "帮助", None))
        self.action.setText(_translate("MainWindow", "使用说明", None))

import app_rc
