# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lineCompUI.ui'
#
# Created: Thu Apr 25 17:28:15 2024
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(350, 381)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_work = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_work.setFont(font)
        self.label_work.setObjectName(_fromUtf8("label_work"))
        self.horizontalLayout_3.addWidget(self.label_work)
        self.label_layers = QtGui.QLabel(self.centralwidget)
        self.label_layers.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_layers.setFont(font)
        self.label_layers.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_layers.setObjectName(_fromUtf8("label_layers"))
        self.horizontalLayout_3.addWidget(self.label_layers)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_baseComp = QtGui.QLineEdit(self.frame)
        self.lineEdit_baseComp.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_baseComp.setFont(font)
        self.lineEdit_baseComp.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_baseComp.setObjectName(_fromUtf8("lineEdit_baseComp"))
        self.gridLayout_2.addWidget(self.lineEdit_baseComp, 1, 1, 1, 1)
        self.lineEdit_impComp = QtGui.QLineEdit(self.frame)
        self.lineEdit_impComp.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_impComp.setFont(font)
        self.lineEdit_impComp.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_impComp.setObjectName(_fromUtf8("lineEdit_impComp"))
        self.gridLayout_2.addWidget(self.lineEdit_impComp, 1, 3, 1, 1)
        self.lineEdit_cuComp = QtGui.QLineEdit(self.frame)
        self.lineEdit_cuComp.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_cuComp.setFont(font)
        self.lineEdit_cuComp.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_cuComp.setObjectName(_fromUtf8("lineEdit_cuComp"))
        self.gridLayout_2.addWidget(self.lineEdit_cuComp, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_bigBGA = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_bigBGA.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_bigBGA.setFont(font)
        self.lineEdit_bigBGA.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_bigBGA.setObjectName(_fromUtf8("lineEdit_bigBGA"))
        self.gridLayout.addWidget(self.lineEdit_bigBGA, 3, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 3, 1, 1)
        self.lineEdit_smallBGA = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_smallBGA.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_smallBGA.setFont(font)
        self.lineEdit_smallBGA.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_smallBGA.setObjectName(_fromUtf8("lineEdit_smallBGA"))
        self.gridLayout.addWidget(self.lineEdit_smallBGA, 3, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 3)
        self.lineEdit_bigSMD = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_bigSMD.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_bigSMD.setFont(font)
        self.lineEdit_bigSMD.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_bigSMD.setObjectName(_fromUtf8("lineEdit_bigSMD"))
        self.gridLayout.addWidget(self.lineEdit_bigSMD, 4, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 3, 1, 1)
        self.lineEdit_smallSMD = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_smallSMD.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_smallSMD.setFont(font)
        self.lineEdit_smallSMD.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_smallSMD.setObjectName(_fromUtf8("lineEdit_smallSMD"))
        self.gridLayout.addWidget(self.lineEdit_smallSMD, 4, 2, 1, 1)
        self.lineEdit_otherPadComp = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_otherPadComp.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_otherPadComp.setFont(font)
        self.lineEdit_otherPadComp.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_otherPadComp.setObjectName(_fromUtf8("lineEdit_otherPadComp"))
        self.gridLayout.addWidget(self.lineEdit_otherPadComp, 5, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_close = QtGui.QPushButton(self.centralwidget)
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_close, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HDI线路预补偿程序", None))
        self.label.setText(_translate("MainWindow", "HDI线路预补偿程序", None))
        self.label_work.setText(_translate("MainWindow", "当前工作层为：", None))
        self.label_layers.setText(_translate("MainWindow", "xxx", None))
        self.label_2.setText(_translate("MainWindow", "选择铜厚范围", None))
        self.label_4.setText(_translate("MainWindow", "阻抗线补偿", None))
        self.label_3.setText(_translate("MainWindow", "一般线补偿", None))
        self.label_5.setText(_translate("MainWindow", "铜皮补偿", None))
        self.label_15.setText(_translate("MainWindow", "线路补偿:", None))
        self.label_6.setText(_translate("MainWindow", "<=12mil BGA", None))
        self.label_8.setText(_translate("MainWindow", "<=12mil SMD", None))
        self.label_7.setText(_translate("MainWindow", ">12mil BGA", None))
        self.label_11.setText(_translate("MainWindow", "无SMD、BGA属性PAD补偿", None))
        self.label_10.setText(_translate("MainWindow", ">12mil SMD", None))
        self.label_14.setText(_translate("MainWindow", "PAD补偿:", None))
        self.pushButton.setText(_translate("MainWindow", "执行", None))
        self.pushButton_close.setText(_translate("MainWindow", "退出", None))
        self.label_9.setText(_translate("MainWindow", "版权所有：胜宏科技 版本: 日期：", None))

