# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OBUIV1.ui'
#
# Created: Mon Sep 30 16:33:06 2024
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(446, 333)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/png/img/Logo.xpm")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_supply = QtGui.QComboBox(self.frame)
        self.comboBox_supply.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_supply.setObjectName(_fromUtf8("comboBox_supply"))
        self.comboBox_supply.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_supply)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox_ob = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_ob.setAutoFillBackground(False)
        self.groupBox_ob.setStyleSheet(_fromUtf8("QGroupBox#groupBox_ob{border:1px solid #000000;}"))
        self.groupBox_ob.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_ob.setObjectName(_fromUtf8("groupBox_ob"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_ob)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.widget = QtGui.QWidget(self.groupBox_ob)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.radioButton_normal = QtGui.QRadioButton(self.widget)
        self.radioButton_normal.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButton_normal.setObjectName(_fromUtf8("radioButton_normal"))
        self.horizontalLayout_9.addWidget(self.radioButton_normal)
        self.radioButton_b74 = QtGui.QRadioButton(self.widget)
        self.radioButton_b74.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButton_b74.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButton_b74.setObjectName(_fromUtf8("radioButton_b74"))
        self.horizontalLayout_9.addWidget(self.radioButton_b74)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.gridLayout_7.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_addsteps = QtGui.QWidget(self.groupBox_ob)
        self.widget_addsteps.setObjectName(_fromUtf8("widget_addsteps"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_addsteps)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_15 = QtGui.QLabel(self.widget_addsteps)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_11.addWidget(self.label_15)
        self.checkBox_edit = QtGui.QCheckBox(self.widget_addsteps)
        self.checkBox_edit.setObjectName(_fromUtf8("checkBox_edit"))
        self.horizontalLayout_11.addWidget(self.checkBox_edit)
        self.checkBox_set = QtGui.QCheckBox(self.widget_addsteps)
        self.checkBox_set.setObjectName(_fromUtf8("checkBox_set"))
        self.horizontalLayout_11.addWidget(self.checkBox_set)
        self.checkBox_icg = QtGui.QCheckBox(self.widget_addsteps)
        self.checkBox_icg.setObjectName(_fromUtf8("checkBox_icg"))
        self.horizontalLayout_11.addWidget(self.checkBox_icg)
        self.gridLayout_7.addWidget(self.widget_addsteps, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_ob)
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setAutoFillBackground(False)
        self.widget_3.setStyleSheet(_fromUtf8("QWidget#widget_3{border:1px solid #000000;}"))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_baozhuang = QtGui.QCheckBox(self.widget_3)
        self.checkBox_baozhuang.setChecked(True)
        self.checkBox_baozhuang.setObjectName(_fromUtf8("checkBox_baozhuang"))
        self.gridLayout_3.addWidget(self.checkBox_baozhuang, 6, 0, 1, 1)
        self.checkBox_obmm = QtGui.QCheckBox(self.widget_3)
        self.checkBox_obmm.setChecked(True)
        self.checkBox_obmm.setObjectName(_fromUtf8("checkBox_obmm"))
        self.gridLayout_3.addWidget(self.checkBox_obmm, 5, 0, 1, 1)
        self.widget_ob_bz = QtGui.QWidget(self.widget_3)
        self.widget_ob_bz.setObjectName(_fromUtf8("widget_ob_bz"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_ob_bz)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.side_bz = QtGui.QComboBox(self.widget_ob_bz)
        self.side_bz.setObjectName(_fromUtf8("side_bz"))
        self.side_bz.addItem(_fromUtf8(""))
        self.side_bz.addItem(_fromUtf8(""))
        self.side_bz.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.side_bz)
        self.layer_bz = QtGui.QComboBox(self.widget_ob_bz)
        self.layer_bz.setObjectName(_fromUtf8("layer_bz"))
        self.layer_bz.addItem(_fromUtf8(""))
        self.layer_bz.addItem(_fromUtf8(""))
        self.layer_bz.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.layer_bz)
        self.comboBox_bz_date = QtGui.QComboBox(self.widget_ob_bz)
        self.comboBox_bz_date.setEnabled(True)
        self.comboBox_bz_date.setObjectName(_fromUtf8("comboBox_bz_date"))
        self.comboBox_bz_date.addItem(_fromUtf8(""))
        self.comboBox_bz_date.addItem(_fromUtf8(""))
        self.comboBox_bz_date.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_bz_date)
        self.bz_other_date = QtGui.QLineEdit(self.widget_ob_bz)
        self.bz_other_date.setEnabled(False)
        self.bz_other_date.setMaximumSize(QtCore.QSize(100, 16777215))
        self.bz_other_date.setInputMask(_fromUtf8(""))
        self.bz_other_date.setText(_fromUtf8(""))
        self.bz_other_date.setObjectName(_fromUtf8("bz_other_date"))
        self.horizontalLayout_4.addWidget(self.bz_other_date)
        self.gridLayout_3.addWidget(self.widget_ob_bz, 6, 1, 1, 3)
        self.widget_ob_bc = QtGui.QWidget(self.widget_3)
        self.widget_ob_bc.setObjectName(_fromUtf8("widget_ob_bc"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_ob_bc)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.side_bc = QtGui.QComboBox(self.widget_ob_bc)
        self.side_bc.setObjectName(_fromUtf8("side_bc"))
        self.side_bc.addItem(_fromUtf8(""))
        self.side_bc.addItem(_fromUtf8(""))
        self.side_bc.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.side_bc)
        self.layer_bc = QtGui.QComboBox(self.widget_ob_bc)
        self.layer_bc.setObjectName(_fromUtf8("layer_bc"))
        self.layer_bc.addItem(_fromUtf8(""))
        self.layer_bc.addItem(_fromUtf8(""))
        self.layer_bc.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.layer_bc)
        self.comboBox_bc = QtGui.QComboBox(self.widget_ob_bc)
        self.comboBox_bc.setObjectName(_fromUtf8("comboBox_bc"))
        self.comboBox_bc.addItem(_fromUtf8(""))
        self.comboBox_bc.addItem(_fromUtf8(""))
        self.comboBox_bc.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_bc)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addWidget(self.widget_ob_bc, 2, 1, 1, 3)
        self.widget_ob_mm = QtGui.QWidget(self.widget_3)
        self.widget_ob_mm.setObjectName(_fromUtf8("widget_ob_mm"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_ob_mm)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.side_mm = QtGui.QComboBox(self.widget_ob_mm)
        self.side_mm.setObjectName(_fromUtf8("side_mm"))
        self.side_mm.addItem(_fromUtf8(""))
        self.side_mm.addItem(_fromUtf8(""))
        self.side_mm.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.side_mm)
        self.layer_mm = QtGui.QComboBox(self.widget_ob_mm)
        self.layer_mm.setObjectName(_fromUtf8("layer_mm"))
        self.layer_mm.addItem(_fromUtf8(""))
        self.layer_mm.addItem(_fromUtf8(""))
        self.layer_mm.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.layer_mm)
        self.comboBox_mm = QtGui.QComboBox(self.widget_ob_mm)
        self.comboBox_mm.setObjectName(_fromUtf8("comboBox_mm"))
        self.comboBox_mm.addItem(_fromUtf8(""))
        self.comboBox_mm.addItem(_fromUtf8(""))
        self.comboBox_mm.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_mm)
        self.mm_polarity = QtGui.QComboBox(self.widget_ob_mm)
        self.mm_polarity.setObjectName(_fromUtf8("mm_polarity"))
        self.mm_polarity.addItem(_fromUtf8(""))
        self.mm_polarity.addItem(_fromUtf8(""))
        self.mm_polarity.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.mm_polarity)
        self.gridLayout_3.addWidget(self.widget_ob_mm, 5, 1, 1, 3)
        self.checkBox_ob2dbc = QtGui.QCheckBox(self.widget_3)
        self.checkBox_ob2dbc.setChecked(True)
        self.checkBox_ob2dbc.setTristate(False)
        self.checkBox_ob2dbc.setObjectName(_fromUtf8("checkBox_ob2dbc"))
        self.gridLayout_3.addWidget(self.checkBox_ob2dbc, 2, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.widget_3)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_9 = QtGui.QLabel(self.widget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_11 = QtGui.QLabel(self.widget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.widget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.widget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.gridLayout_3.addWidget(self.widget_2, 0, 1, 2, 3)
        self.verticalLayout.addWidget(self.widget_3)
        self.label_tips = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setBold(True)
        font.setWeight(75)
        self.label_tips.setFont(font)
        self.label_tips.setObjectName(_fromUtf8("label_tips"))
        self.verticalLayout.addWidget(self.label_tips)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.pushButton_apply = QtGui.QPushButton(self.centralwidget)
        self.pushButton_apply.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_apply.setMaximumSize(QtCore.QSize(200, 35))
        self.pushButton_apply.setObjectName(_fromUtf8("pushButton_apply"))
        self.horizontalLayout_6.addWidget(self.pushButton_apply)
        self.pushButton_close = QtGui.QPushButton(self.centralwidget)
        self.pushButton_close.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_close.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.horizontalLayout_6.addWidget(self.pushButton_close)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.label_bottom = QtGui.QLabel(self.centralwidget)
        self.label_bottom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bottom.setObjectName(_fromUtf8("label_bottom"))
        self.verticalLayout.addWidget(self.label_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_2.setBuddy(self.comboBox_supply)
        self.label_10.setBuddy(self.radioButton_b74)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_close, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.checkBox_ob2dbc, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget_ob_bc.setEnabled)
        QtCore.QObject.connect(self.checkBox_obmm, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget_ob_mm.setEnabled)
        QtCore.QObject.connect(self.checkBox_baozhuang, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget_ob_bz.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Text添加", None))
        self.label.setText(_translate("MainWindow", "奥宝Text类型明码二维码添加", None))
        self.label_2.setText(_translate("MainWindow", "选择机台厂商", None))
        self.comboBox_supply.setItemText(0, _translate("MainWindow", "奥宝", None))
        self.groupBox_ob.setTitle(_translate("MainWindow", "奥宝二维码及明码", None))
        self.label_10.setText(_translate("MainWindow", "添加类型", None))
        self.radioButton_normal.setText(_translate("MainWindow", "常规系列", None))
        self.radioButton_b74.setText(_translate("MainWindow", "B74系列", None))
        self.label_15.setText(_translate("MainWindow", "添加Step类", None))
        self.checkBox_edit.setText(_translate("MainWindow", "edit", None))
        self.checkBox_set.setText(_translate("MainWindow", "set", None))
        self.checkBox_icg.setText(_translate("MainWindow", "icg", None))
        self.checkBox_baozhuang.setText(_translate("MainWindow", "包装码", None))
        self.checkBox_obmm.setText(_translate("MainWindow", "明码", None))
        self.side_bz.setItemText(0, _translate("MainWindow", "请选择", None))
        self.side_bz.setItemText(1, _translate("MainWindow", "正面", None))
        self.side_bz.setItemText(2, _translate("MainWindow", "反面", None))
        self.layer_bz.setItemText(0, _translate("MainWindow", "请选择", None))
        self.layer_bz.setItemText(1, _translate("MainWindow", "防焊", None))
        self.layer_bz.setItemText(2, _translate("MainWindow", "文字", None))
        self.comboBox_bz_date.setItemText(0, _translate("MainWindow", "$$YY$$WW", None))
        self.comboBox_bz_date.setItemText(1, _translate("MainWindow", "$$WW$$YY", None))
        self.comboBox_bz_date.setItemText(2, _translate("MainWindow", "其他", None))
        self.bz_other_date.setToolTip(_translate("MainWindow", "<html><head/><body><p>只能输入$ W Y M D 的组合</p></body></html>", None))
        self.side_bc.setItemText(0, _translate("MainWindow", "请选择", None))
        self.side_bc.setItemText(1, _translate("MainWindow", "正面", None))
        self.side_bc.setItemText(2, _translate("MainWindow", "反面", None))
        self.layer_bc.setItemText(0, _translate("MainWindow", "请选择", None))
        self.layer_bc.setItemText(1, _translate("MainWindow", "防焊", None))
        self.layer_bc.setItemText(2, _translate("MainWindow", "线路", None))
        self.comboBox_bc.setItemText(0, _translate("MainWindow", "4.5", None))
        self.comboBox_bc.setItemText(1, _translate("MainWindow", "5", None))
        self.comboBox_bc.setItemText(2, _translate("MainWindow", "4", None))
        self.side_mm.setItemText(0, _translate("MainWindow", "请选择", None))
        self.side_mm.setItemText(1, _translate("MainWindow", "正面", None))
        self.side_mm.setItemText(2, _translate("MainWindow", "反面", None))
        self.layer_mm.setItemText(0, _translate("MainWindow", "请选择", None))
        self.layer_mm.setItemText(1, _translate("MainWindow", "防焊", None))
        self.layer_mm.setItemText(2, _translate("MainWindow", "线路", None))
        self.comboBox_mm.setItemText(0, _translate("MainWindow", "4/6制_8.9408x1.1176mm", None))
        self.comboBox_mm.setItemText(1, _translate("MainWindow", "3/6制_6.7056x0.8382mm", None))
        self.comboBox_mm.setItemText(2, _translate("MainWindow", "2/6制_4.4704x0.5588mm", None))
        self.mm_polarity.setItemText(0, _translate("MainWindow", "请选择", None))
        self.mm_polarity.setItemText(1, _translate("MainWindow", "阴字", None))
        self.mm_polarity.setItemText(2, _translate("MainWindow", "阳字", None))
        self.checkBox_ob2dbc.setText(_translate("MainWindow", "二维码", None))
        self.label_9.setText(_translate("MainWindow", "面向", None))
        self.label_11.setText(_translate("MainWindow", "层别", None))
        self.label_12.setText(_translate("MainWindow", "内容", None))
        self.label_13.setText(_translate("MainWindow", "扩展", None))
        self.label_tips.setText(_translate("MainWindow", "Tips", None))
        self.pushButton_apply.setText(_translate("MainWindow", "执行", None))
        self.pushButton_close.setText(_translate("MainWindow", "退出", None))
        self.label_bottom.setText(_translate("MainWindow", "版权所有：胜宏科技 版本：V2.0", None))

