# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUIV7.ui'
#
# Created: Fri Nov 05 10:18:51 2021
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(278, 854)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/Logo.xpm")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_supply = QtGui.QComboBox(self.frame)
        self.comboBox_supply.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_supply.setObjectName(_fromUtf8("comboBox_supply"))
        self.comboBox_supply.addItem(_fromUtf8(""))
        self.comboBox_supply.addItem(_fromUtf8(""))
        self.comboBox_supply.addItem(_fromUtf8(""))
        self.comboBox_supply.addItem(_fromUtf8(""))
        self.comboBox_supply.addItem(_fromUtf8(""))
        self.comboBox_supply.addItem(_fromUtf8(""))
        # self.comboBox_supply.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_supply)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget_paint = QtGui.QWidget(self.frame_3)
        self.widget_paint.setObjectName(_fromUtf8("widget_paint"))
        self.gridLayout_4.addWidget(self.widget_paint, 2, 2, 3, 2)
        self.comboBox_mode = QtGui.QComboBox(self.frame_3)
        self.comboBox_mode.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_mode.setMaximumSize(QtCore.QSize(100, 50))
        self.comboBox_mode.setObjectName(_fromUtf8("comboBox_mode"))
        self.comboBox_mode.addItem(_fromUtf8(""))
        self.comboBox_mode.addItem(_fromUtf8(""))
        self.comboBox_mode.addItem(_fromUtf8(""))
        self.comboBox_mode.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_mode, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setMinimumSize(QtCore.QSize(50, 25))
        self.label_3.setMaximumSize(QtCore.QSize(100, 50))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_dateformat = QtGui.QLabel(self.frame_3)
        self.label_dateformat.setEnabled(False)
        self.label_dateformat.setMaximumSize(QtCore.QSize(100, 50))
        self.label_dateformat.setObjectName(_fromUtf8("label_dateformat"))
        self.gridLayout_4.addWidget(self.label_dateformat, 0, 2, 1, 1)
        self.comboBox_date = QtGui.QComboBox(self.frame_3)
        self.comboBox_date.setEnabled(False)
        self.comboBox_date.setObjectName(_fromUtf8("comboBox_date"))
        self.comboBox_date.addItem(_fromUtf8(""))
        self.comboBox_date.addItem(_fromUtf8(""))
        self.comboBox_date.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_date, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setMinimumSize(QtCore.QSize(50, 25))
        self.label_4.setMaximumSize(QtCore.QSize(200, 35))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox_angle = QtGui.QComboBox(self.frame_3)
        self.comboBox_angle.setMinimumSize(QtCore.QSize(20, 25))
        self.comboBox_angle.setMaximumSize(QtCore.QSize(100, 50))
        self.comboBox_angle.setObjectName(_fromUtf8("comboBox_angle"))
        self.comboBox_angle.addItem(_fromUtf8(""))
        self.comboBox_angle.addItem(_fromUtf8(""))
        self.comboBox_angle.addItem(_fromUtf8(""))
        self.comboBox_angle.addItem(_fromUtf8(""))
        self.comboBox_angle.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_angle, 1, 1, 1, 1)
        self.lineEdit_freeangle = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_freeangle.setEnabled(False)
        self.lineEdit_freeangle.setMinimumSize(QtCore.QSize(20, 25))
        self.lineEdit_freeangle.setMaximumSize(QtCore.QSize(100, 50))
        self.lineEdit_freeangle.setMaxLength(6)
        self.lineEdit_freeangle.setObjectName(_fromUtf8("lineEdit_freeangle"))
        self.gridLayout_4.addWidget(self.lineEdit_freeangle, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setMinimumSize(QtCore.QSize(50, 25))
        self.label_8.setMaximumSize(QtCore.QSize(200, 35))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEdit_width = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_width.setMinimumSize(QtCore.QSize(10, 25))
        self.lineEdit_width.setMaximumSize(QtCore.QSize(100, 75))
        self.lineEdit_width.setMaxLength(10)
        self.lineEdit_width.setObjectName(_fromUtf8("lineEdit_width"))
        self.gridLayout_4.addWidget(self.lineEdit_width, 4, 1, 1, 1)
        self.lineEdit_length = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_length.setMinimumSize(QtCore.QSize(10, 25))
        self.lineEdit_length.setMaximumSize(QtCore.QSize(100, 75))
        self.lineEdit_length.setMaxLength(10)
        self.lineEdit_length.setObjectName(_fromUtf8("lineEdit_length"))
        self.gridLayout_4.addWidget(self.lineEdit_length, 3, 1, 1, 1)
        self.label_attr = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.label_attr.setFont(font)
        self.label_attr.setObjectName(_fromUtf8("label_attr"))
        self.gridLayout_4.addWidget(self.label_attr, 1, 3, 1, 1)
        self.comboBox_mirror = QtGui.QComboBox(self.frame_3)
        self.comboBox_mirror.setMinimumSize(QtCore.QSize(20, 25))
        self.comboBox_mirror.setMaximumSize(QtCore.QSize(100, 50))
        self.comboBox_mirror.setObjectName(_fromUtf8("comboBox_mirror"))
        self.comboBox_mirror.addItem(_fromUtf8(""))
        self.comboBox_mirror.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_mirror, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setMinimumSize(QtCore.QSize(50, 25))
        self.label_6.setMaximumSize(QtCore.QSize(100, 50))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setMinimumSize(QtCore.QSize(50, 25))
        self.label_5.setMaximumSize(QtCore.QSize(100, 50))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.groupBox_mm = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_mm.setObjectName(_fromUtf8("groupBox_mm"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_mm)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.checkBox_2dbc_by = QtGui.QCheckBox(self.groupBox_mm)
        self.checkBox_2dbc_by.setChecked(True)
        self.checkBox_2dbc_by.setObjectName(_fromUtf8("checkBox_2dbc_by"))
        self.gridLayout_6.addWidget(self.checkBox_2dbc_by, 1, 0, 1, 2)
        self.label_mm_height = QtGui.QLabel(self.groupBox_mm)
        self.label_mm_height.setObjectName(_fromUtf8("label_mm_height"))
        self.gridLayout_6.addWidget(self.label_mm_height, 0, 2, 1, 1)
        self.label_2dbc_by = QtGui.QLabel(self.groupBox_mm)
        self.label_2dbc_by.setObjectName(_fromUtf8("label_2dbc_by"))
        self.gridLayout_6.addWidget(self.label_2dbc_by, 1, 2, 1, 1)
        self.lineEdit_mmheight = QtGui.QLineEdit(self.groupBox_mm)
        self.lineEdit_mmheight.setObjectName(_fromUtf8("lineEdit_mmheight"))
        self.gridLayout_6.addWidget(self.lineEdit_mmheight, 0, 3, 1, 1)
        self.lineEdit_mm_by = QtGui.QLineEdit(self.groupBox_mm)
        self.lineEdit_mm_by.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_mm_by.setObjectName(_fromUtf8("lineEdit_mm_by"))
        self.gridLayout_6.addWidget(self.lineEdit_mm_by, 2, 3, 1, 1)
        self.lineEdit_2dbc_by = QtGui.QLineEdit(self.groupBox_mm)
        self.lineEdit_2dbc_by.setObjectName(_fromUtf8("lineEdit_2dbc_by"))
        self.gridLayout_6.addWidget(self.lineEdit_2dbc_by, 1, 3, 1, 1)
        self.label_mm_length = QtGui.QLabel(self.groupBox_mm)
        self.label_mm_length.setObjectName(_fromUtf8("label_mm_length"))
        self.gridLayout_6.addWidget(self.label_mm_length, 0, 0, 1, 1)
        self.lineEdit_mmlength = QtGui.QLineEdit(self.groupBox_mm)
        self.lineEdit_mmlength.setObjectName(_fromUtf8("lineEdit_mmlength"))
        self.gridLayout_6.addWidget(self.lineEdit_mmlength, 0, 1, 1, 1)
        self.label_mm_by = QtGui.QLabel(self.groupBox_mm)
        self.label_mm_by.setObjectName(_fromUtf8("label_mm_by"))
        self.gridLayout_6.addWidget(self.label_mm_by, 2, 2, 1, 1)
        self.checkBox_pnl_2dbc = QtGui.QCheckBox(self.groupBox_mm)
        self.checkBox_pnl_2dbc.setObjectName(_fromUtf8("checkBox_pnl_2dbc"))
        self.gridLayout_6.addWidget(self.checkBox_pnl_2dbc, 3, 0, 1, 4)
        self.checkBox_mm_by = QtGui.QCheckBox(self.groupBox_mm)
        self.checkBox_mm_by.setChecked(True)
        self.checkBox_mm_by.setObjectName(_fromUtf8("checkBox_mm_by"))
        self.gridLayout_6.addWidget(self.checkBox_mm_by, 2, 0, 1, 2)
        self.checkBox_manumark = QtGui.QCheckBox(self.groupBox_mm)
        self.checkBox_manumark.setObjectName(_fromUtf8("checkBox_manumark"))
        self.gridLayout_6.addWidget(self.checkBox_manumark, 4, 0, 1, 4)
        self.verticalLayout.addWidget(self.groupBox_mm)
        self.groupBox_ob = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_ob.setAutoFillBackground(False)
        self.groupBox_ob.setStyleSheet(_fromUtf8("QGroupBox#groupBox_ob{border:1px solid #000000;}"))
        self.groupBox_ob.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_ob.setObjectName(_fromUtf8("groupBox_ob"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_ob)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget = QtGui.QWidget(self.groupBox_ob)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.radioButton_normal = QtGui.QRadioButton(self.widget)
        self.radioButton_normal.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButton_normal.setObjectName(_fromUtf8("radioButton_normal"))
        self.horizontalLayout_9.addWidget(self.radioButton_normal)
        self.radioButton_b74 = QtGui.QRadioButton(self.widget)
        self.radioButton_b74.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButton_b74.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButton_b74.setObjectName(_fromUtf8("radioButton_b74"))
        self.horizontalLayout_9.addWidget(self.radioButton_b74)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.groupBox_ob)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_11 = QtGui.QLabel(self.widget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.checkBox_baozhuang = QtGui.QCheckBox(self.widget_2)
        self.checkBox_baozhuang.setObjectName(_fromUtf8("checkBox_baozhuang"))
        self.horizontalLayout_4.addWidget(self.checkBox_baozhuang)
        self.checkBox_ob2dbc = QtGui.QCheckBox(self.widget_2)
        self.checkBox_ob2dbc.setObjectName(_fromUtf8("checkBox_ob2dbc"))
        self.horizontalLayout_4.addWidget(self.checkBox_ob2dbc)
        self.checkBox_obmm = QtGui.QCheckBox(self.widget_2)
        self.checkBox_obmm.setObjectName(_fromUtf8("checkBox_obmm"))
        self.horizontalLayout_4.addWidget(self.checkBox_obmm)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_addsteps = QtGui.QWidget(self.groupBox_ob)
        self.widget_addsteps.setObjectName(_fromUtf8("widget_addsteps"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_addsteps)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_15 = QtGui.QLabel(self.widget_addsteps)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_11.addWidget(self.label_15)
        self.checkBox_edit = QtGui.QCheckBox(self.widget_addsteps)
        self.checkBox_edit.setObjectName(_fromUtf8("checkBox_edit"))
        self.horizontalLayout_11.addWidget(self.checkBox_edit)
        self.checkBox_set = QtGui.QCheckBox(self.widget_addsteps)
        self.checkBox_set.setObjectName(_fromUtf8("checkBox_set"))
        self.horizontalLayout_11.addWidget(self.checkBox_set)
        self.checkBox_icg = QtGui.QCheckBox(self.widget_addsteps)
        self.checkBox_icg.setObjectName(_fromUtf8("checkBox_icg"))
        self.horizontalLayout_11.addWidget(self.checkBox_icg)
        self.verticalLayout_2.addWidget(self.widget_addsteps)
        self.widget_cu_thick = QtGui.QWidget(self.groupBox_ob)
        self.widget_cu_thick.setEnabled(False)
        self.widget_cu_thick.setObjectName(_fromUtf8("widget_cu_thick"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_cu_thick)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_16 = QtGui.QLabel(self.widget_cu_thick)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_10.addWidget(self.label_16)
        self.lineEdit_ob2dbc = QtGui.QLineEdit(self.widget_cu_thick)
        self.lineEdit_ob2dbc.setObjectName(_fromUtf8("lineEdit_ob2dbc"))
        self.horizontalLayout_10.addWidget(self.lineEdit_ob2dbc)
        self.checkBox_cuthick = QtGui.QCheckBox(self.widget_cu_thick)
        self.checkBox_cuthick.setObjectName(_fromUtf8("checkBox_cuthick"))
        self.horizontalLayout_10.addWidget(self.checkBox_cuthick)
        self.verticalLayout_2.addWidget(self.widget_cu_thick)
        self.widget_etch_side = QtGui.QWidget(self.groupBox_ob)
        self.widget_etch_side.setEnabled(False)
        self.widget_etch_side.setObjectName(_fromUtf8("widget_etch_side"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_etch_side)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_etchside = QtGui.QLabel(self.widget_etch_side)
        self.label_etchside.setObjectName(_fromUtf8("label_etchside"))
        self.horizontalLayout_2.addWidget(self.label_etchside)
        self.radioButton_obtop = QtGui.QRadioButton(self.widget_etch_side)
        self.radioButton_obtop.setObjectName(_fromUtf8("radioButton_obtop"))
        self.horizontalLayout_2.addWidget(self.radioButton_obtop)
        self.radioButton_obbot = QtGui.QRadioButton(self.widget_etch_side)
        self.radioButton_obbot.setObjectName(_fromUtf8("radioButton_obbot"))
        self.horizontalLayout_2.addWidget(self.radioButton_obbot)
        self.verticalLayout_2.addWidget(self.widget_etch_side)
        self.widget_etch_text = QtGui.QWidget(self.groupBox_ob)
        self.widget_etch_text.setEnabled(False)
        self.widget_etch_text.setObjectName(_fromUtf8("widget_etch_text"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_etch_text)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_13 = QtGui.QLabel(self.widget_etch_text)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.radioButton_neg = QtGui.QRadioButton(self.widget_etch_text)
        self.radioButton_neg.setObjectName(_fromUtf8("radioButton_neg"))
        self.horizontalLayout_5.addWidget(self.radioButton_neg)
        self.radioButton_pos = QtGui.QRadioButton(self.widget_etch_text)
        self.radioButton_pos.setObjectName(_fromUtf8("radioButton_pos"))
        self.horizontalLayout_5.addWidget(self.radioButton_pos)
        self.verticalLayout_2.addWidget(self.widget_etch_text)
        self.widget_bzlayer = QtGui.QWidget(self.groupBox_ob)
        self.widget_bzlayer.setEnabled(False)
        self.widget_bzlayer.setObjectName(_fromUtf8("widget_bzlayer"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_bzlayer)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.widget_bzlayer)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.radioButton_sm = QtGui.QRadioButton(self.widget_bzlayer)
        self.radioButton_sm.setObjectName(_fromUtf8("radioButton_sm"))
        self.horizontalLayout_7.addWidget(self.radioButton_sm)
        self.radioButton_ss = QtGui.QRadioButton(self.widget_bzlayer)
        self.radioButton_ss.setObjectName(_fromUtf8("radioButton_ss"))
        self.horizontalLayout_7.addWidget(self.radioButton_ss)
        self.verticalLayout_2.addWidget(self.widget_bzlayer)
        self.widget_bzside = QtGui.QWidget(self.groupBox_ob)
        self.widget_bzside.setEnabled(False)
        self.widget_bzside.setObjectName(_fromUtf8("widget_bzside"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_bzside)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_12 = QtGui.QLabel(self.widget_bzside)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        self.radioButton_bztop = QtGui.QRadioButton(self.widget_bzside)
        self.radioButton_bztop.setObjectName(_fromUtf8("radioButton_bztop"))
        self.horizontalLayout_8.addWidget(self.radioButton_bztop)
        self.radioButton_bzbot = QtGui.QRadioButton(self.widget_bzside)
        self.radioButton_bzbot.setObjectName(_fromUtf8("radioButton_bzbot"))
        self.horizontalLayout_8.addWidget(self.radioButton_bzbot)
        self.verticalLayout_2.addWidget(self.widget_bzside)
        self.widget_bzdate = QtGui.QWidget(self.groupBox_ob)
        self.widget_bzdate.setEnabled(True)
        self.widget_bzdate.setObjectName(_fromUtf8("widget_bzdate"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_bzdate)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_bzdate = QtGui.QLabel(self.widget_bzdate)
        self.label_bzdate.setEnabled(True)
        self.label_bzdate.setMaximumSize(QtCore.QSize(100, 50))
        self.label_bzdate.setObjectName(_fromUtf8("label_bzdate"))
        self.horizontalLayout_3.addWidget(self.label_bzdate)
        self.comboBox_bz_date = QtGui.QComboBox(self.widget_bzdate)
        self.comboBox_bz_date.setEnabled(True)
        self.comboBox_bz_date.setObjectName(_fromUtf8("comboBox_bz_date"))
        self.comboBox_bz_date.addItem(_fromUtf8(""))
        self.comboBox_bz_date.addItem(_fromUtf8(""))
        self.comboBox_bz_date.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_bz_date)
        self.bz_other_date = QtGui.QLineEdit(self.widget_bzdate)
        self.bz_other_date.setEnabled(False)
        self.bz_other_date.setMaximumSize(QtCore.QSize(100, 16777215))
        self.bz_other_date.setObjectName(_fromUtf8("bz_other_date"))
        self.horizontalLayout_3.addWidget(self.bz_other_date)
        self.verticalLayout_2.addWidget(self.widget_bzdate)
        self.verticalLayout.addWidget(self.groupBox_ob)
        self.label_tips = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setBold(True)
        font.setWeight(75)
        self.label_tips.setFont(font)
        self.label_tips.setObjectName(_fromUtf8("label_tips"))
        self.verticalLayout.addWidget(self.label_tips)
        self.frame_pnl = QtGui.QFrame(self.centralwidget)
        self.frame_pnl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_pnl.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_pnl.setObjectName(_fromUtf8("frame_pnl"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_pnl)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_pnl = QtGui.QLabel(self.frame_pnl)
        self.label_pnl.setObjectName(_fromUtf8("label_pnl"))
        self.gridLayout_5.addWidget(self.label_pnl, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_pnl)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.listWidget_layerlist = QtGui.QListWidget(self.frame_2)
        self.listWidget_layerlist.setMinimumSize(QtCore.QSize(100, 50))
        self.listWidget_layerlist.setMaximumSize(QtCore.QSize(1080, 200))
        self.listWidget_layerlist.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget_layerlist.setObjectName(_fromUtf8("listWidget_layerlist"))
        self.gridLayout.addWidget(self.listWidget_layerlist, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pushButton_apply = QtGui.QPushButton(self.centralwidget)
        self.pushButton_apply.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_apply.setMaximumSize(QtCore.QSize(200, 35))
        self.pushButton_apply.setObjectName(_fromUtf8("pushButton_apply"))
        self.horizontalLayout_6.addWidget(self.pushButton_apply)
        self.pushButton_close = QtGui.QPushButton(self.centralwidget)
        self.pushButton_close.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_close.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.horizontalLayout_6.addWidget(self.pushButton_close)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.label_bottom = QtGui.QLabel(self.centralwidget)
        self.label_bottom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bottom.setObjectName(_fromUtf8("label_bottom"))
        self.verticalLayout.addWidget(self.label_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_2.setBuddy(self.comboBox_supply)
        self.label_3.setBuddy(self.comboBox_mode)
        self.label_dateformat.setBuddy(self.comboBox_date)
        self.label_4.setBuddy(self.comboBox_angle)
        self.label_8.setBuddy(self.comboBox_mirror)
        self.label_6.setBuddy(self.lineEdit_width)
        self.label_5.setBuddy(self.lineEdit_length)
        self.label_mm_height.setBuddy(self.lineEdit_mmheight)
        self.label_2dbc_by.setBuddy(self.lineEdit_2dbc_by)
        self.label_mm_length.setBuddy(self.lineEdit_mmlength)
        self.label_mm_by.setBuddy(self.lineEdit_mm_by)
        self.label_10.setBuddy(self.radioButton_b74)
        self.label_11.setBuddy(self.checkBox_baozhuang)
        self.label_etchside.setBuddy(self.radioButton_obtop)
        self.label_9.setBuddy(self.radioButton_sm)
        self.label_12.setBuddy(self.radioButton_bztop)
        self.label_bzdate.setBuddy(self.comboBox_date)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_close, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.checkBox_2dbc_by, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_2dbc_by.setEnabled)
        QtCore.QObject.connect(self.checkBox_mm_by, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_mm_by.setEnabled)
        QtCore.QObject.connect(self.checkBox_baozhuang, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget_bzlayer.setEnabled)
        QtCore.QObject.connect(self.checkBox_baozhuang, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget_bzside.setEnabled)
        QtCore.QObject.connect(self.checkBox_baozhuang, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget_bzdate.setEnabled)
        QtCore.QObject.connect(self.radioButton_b74, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.checkBox_baozhuang.setDisabled)
        QtCore.QObject.connect(self.radioButton_b74, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.checkBox_ob2dbc.setChecked)
        QtCore.QObject.connect(self.radioButton_b74, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.checkBox_obmm.setDisabled)
        QtCore.QObject.connect(self.radioButton_normal, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.checkBox_baozhuang.setEnabled)
        QtCore.QObject.connect(self.radioButton_normal, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.checkBox_obmm.setEnabled)
        QtCore.QObject.connect(self.checkBox_ob2dbc, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget_cu_thick.setEnabled)
        QtCore.QObject.connect(self.checkBox_obmm, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget_etch_text.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "symbol生成器", None))
        self.label.setText(_translate("MainWindow", "动态码symbol生成器", None))
        self.label_2.setText(_translate("MainWindow", "选择机台厂商", None))
        self.comboBox_supply.setItemText(0, _translate("MainWindow", "劲鑫喷墨", None))
        self.comboBox_supply.setItemText(1, _translate("MainWindow", "汉印喷墨", None))
        self.comboBox_supply.setItemText(2, _translate("MainWindow", "升达康镭雕", None))
        self.comboBox_supply.setItemText(3, _translate("MainWindow", "A86文字喷墨(MLB)", None))
        self.comboBox_supply.setItemText(4, _translate("MainWindow", "A86文字喷墨(HDI)", None))
        self.comboBox_supply.setItemText(5, _translate("MainWindow", "A81文字喷墨(HDI)", None))
        #周涌通知 取消奥宝选项 单独有个奥宝添加程序 20221210 by lyh
        # self.comboBox_supply.setItemText(6, _translate("MainWindow", "奥宝", None))
        self.comboBox_mode.setItemText(0, _translate("MainWindow", "序列号", None))
        self.comboBox_mode.setItemText(1, _translate("MainWindow", "序列号2", None))
        self.comboBox_mode.setItemText(2, _translate("MainWindow", "周期", None))
        self.comboBox_mode.setItemText(3, _translate("MainWindow", "二维码", None))
        self.label_3.setText(_translate("MainWindow", "添加内容", None))
        self.label_dateformat.setText(_translate("MainWindow", "周期格式", None))
        self.comboBox_date.setItemText(0, _translate("MainWindow", "WWYY", None))
        self.comboBox_date.setItemText(1, _translate("MainWindow", "YYWW", None))
        self.comboBox_date.setItemText(2, _translate("MainWindow", "YYWWD", None))
        self.label_4.setText(_translate("MainWindow", "添加角度", None))
        self.comboBox_angle.setItemText(0, _translate("MainWindow", "0", None))
        self.comboBox_angle.setItemText(1, _translate("MainWindow", "90", None))
        self.comboBox_angle.setItemText(2, _translate("MainWindow", "180", None))
        self.comboBox_angle.setItemText(3, _translate("MainWindow", "270", None))
        self.comboBox_angle.setItemText(4, _translate("MainWindow", "其他", None))
        self.label_8.setText(_translate("MainWindow", "添加镜像", None))
        self.lineEdit_width.setToolTip(_translate("MainWindow", "<html><head/><body><p>选择明码时，不填写此栏位</p></body></html>", None))
        self.lineEdit_length.setToolTip(_translate("MainWindow", "<html><head/><body><p>选择明码时，不填写此栏位</p></body></html>", None))
        self.label_attr.setText(_translate("MainWindow", "属性", None))
        self.comboBox_mirror.setItemText(0, _translate("MainWindow", "否", None))
        self.comboBox_mirror.setItemText(1, _translate("MainWindow", "是", None))
        self.label_6.setText(_translate("MainWindow", "添加高度", None))
        self.label_5.setText(_translate("MainWindow", "添加长度", None))
        self.groupBox_mm.setTitle(_translate("MainWindow", "镭雕二维码选项", None))
        self.checkBox_2dbc_by.setText(_translate("MainWindow", "添加二维码白油块", None))
        self.label_mm_height.setText(_translate("MainWindow", "明码高度", None))
        self.label_2dbc_by.setText(_translate("MainWindow", "白油块大小", None))
        self.lineEdit_mm_by.setToolTip(_translate("MainWindow", "<html><head/><body><p>输入10x2类型字符串</p></body></html>", None))
        self.label_mm_length.setText(_translate("MainWindow", "明码长度", None))
        self.label_mm_by.setText(_translate("MainWindow", "白油块大小", None))
        self.checkBox_pnl_2dbc.setText(_translate("MainWindow", "添加板边二维码coupon", None))
        self.checkBox_mm_by.setText(_translate("MainWindow", "添加明码白油块", None))
        self.checkBox_manumark.setText(_translate("MainWindow", "手动选择光点", None))
        self.groupBox_ob.setTitle(_translate("MainWindow", "奥宝二维码及明码", None))
        self.label_10.setText(_translate("MainWindow", "添加类型", None))
        self.radioButton_normal.setText(_translate("MainWindow", "常规系列", None))
        self.radioButton_b74.setText(_translate("MainWindow", "B74系列", None))
        self.label_11.setText(_translate("MainWindow", "添加内容", None))
        self.checkBox_baozhuang.setText(_translate("MainWindow", "包装码", None))
        self.checkBox_ob2dbc.setText(_translate("MainWindow", "二维码", None))
        self.checkBox_obmm.setText(_translate("MainWindow", "明码", None))
        self.label_15.setText(_translate("MainWindow", "添加Step类", None))
        self.checkBox_edit.setText(_translate("MainWindow", "edit", None))
        self.checkBox_set.setText(_translate("MainWindow", "set", None))
        self.checkBox_icg.setText(_translate("MainWindow", "icg", None))
        self.label_16.setText(_translate("MainWindow", "二维码大小:", None))
        self.lineEdit_ob2dbc.setToolTip(_translate("MainWindow", "<html><head/><body><p>输入单个数字即可，单位默认为MM</p></body></html>", None))
        self.lineEdit_ob2dbc.setText(_translate("MainWindow", "5", None))
        self.checkBox_cuthick.setText(_translate("MainWindow", "面铜大于1.18mil", None))
        self.label_etchside.setText(_translate("MainWindow", "蚀刻码面次", None))
        self.radioButton_obtop.setText(_translate("MainWindow", "正面", None))
        self.radioButton_obbot.setText(_translate("MainWindow", "反面", None))
        self.label_13.setText(_translate("MainWindow", "蚀刻明码", None))
        self.radioButton_neg.setText(_translate("MainWindow", "阴字", None))
        self.radioButton_pos.setText(_translate("MainWindow", "阳字", None))
        self.label_9.setText(_translate("MainWindow", "包装码层别", None))
        self.radioButton_sm.setText(_translate("MainWindow", "防焊", None))
        self.radioButton_ss.setText(_translate("MainWindow", "文字", None))
        self.label_12.setText(_translate("MainWindow", "包装码面次", None))
        self.radioButton_bztop.setText(_translate("MainWindow", "正面", None))
        self.radioButton_bzbot.setText(_translate("MainWindow", "反面", None))
        self.label_bzdate.setText(_translate("MainWindow", "周期格式", None))
        self.comboBox_bz_date.setItemText(0, _translate("MainWindow", "$$YY$$WW", None))
        self.comboBox_bz_date.setItemText(1, _translate("MainWindow", "$$WW$$YY", None))
        self.comboBox_bz_date.setItemText(2, _translate("MainWindow", "其他", None))
        self.bz_other_date.setToolTip(_translate("MainWindow", "<html><head/><body><p>只能输入$ W Y M D 的组合</p></body></html>", None))
        self.label_tips.setText(_translate("MainWindow", "Tips", None))
        self.label_pnl.setText(_translate("MainWindow", "板边自动添加", None))
        self.label_7.setText(_translate("MainWindow", "添加层别:", None))
        self.pushButton_apply.setText(_translate("MainWindow", "执行", None))
        self.pushButton_close.setText(_translate("MainWindow", "退出", None))
        self.label_bottom.setText(_translate("MainWindow", "版权所有：胜宏科技 版本：V2.0", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

