# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\other\window_panel.ui'
#
# Created: Mon Jul 29 11:17:22 2024
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setEnabled(True)
        Form.resize(835, 945)
        Form.setMinimumSize(QtCore.QSize(835, 860))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pic/images/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.topLabel = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topLabel.sizePolicy().hasHeightForWidth())
        self.topLabel.setSizePolicy(sizePolicy)
        self.topLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.topLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.topLabel.setFont(font)
        self.topLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel.setObjectName(_fromUtf8("topLabel"))
        self.verticalLayout.addWidget(self.topLabel)
        self.array_parm_box = QtGui.QGroupBox(Form)
        self.array_parm_box.setMinimumSize(QtCore.QSize(0, 121))
        self.array_parm_box.setObjectName(_fromUtf8("array_parm_box"))
        self.layoutWidget = QtGui.QWidget(self.array_parm_box)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 761, 94))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_array_x_size = QtGui.QLabel(self.layoutWidget)
        self.label_array_x_size.setMinimumSize(QtCore.QSize(80, 25))
        self.label_array_x_size.setMaximumSize(QtCore.QSize(100, 25))
        self.label_array_x_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_array_x_size.setObjectName(_fromUtf8("label_array_x_size"))
        self.gridLayout_2.addWidget(self.label_array_x_size, 0, 2, 1, 1)
        self.panel_x = QtGui.QLineEdit(self.layoutWidget)
        self.panel_x.setMinimumSize(QtCore.QSize(68, 25))
        self.panel_x.setMaximumSize(QtCore.QSize(68, 25))
        self.panel_x.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.panel_x.setObjectName(_fromUtf8("panel_x"))
        self.gridLayout_2.addWidget(self.panel_x, 0, 5, 1, 1)
        self.label_panel_x = QtGui.QLabel(self.layoutWidget)
        self.label_panel_x.setMinimumSize(QtCore.QSize(100, 25))
        self.label_panel_x.setMaximumSize(QtCore.QSize(100, 25))
        self.label_panel_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_panel_x.setObjectName(_fromUtf8("label_panel_x"))
        self.gridLayout_2.addWidget(self.label_panel_x, 0, 4, 1, 1)
        self.label_rout_x = QtGui.QLabel(self.layoutWidget)
        self.label_rout_x.setMinimumSize(QtCore.QSize(100, 25))
        self.label_rout_x.setMaximumSize(QtCore.QSize(100, 25))
        self.label_rout_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rout_x.setObjectName(_fromUtf8("label_rout_x"))
        self.gridLayout_2.addWidget(self.label_rout_x, 0, 6, 1, 1)
        self.array_step = QtGui.QLineEdit(self.layoutWidget)
        self.array_step.setEnabled(False)
        self.array_step.setMinimumSize(QtCore.QSize(68, 25))
        self.array_step.setMaximumSize(QtCore.QSize(68, 25))
        self.array_step.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.array_step.setText(_fromUtf8(""))
        self.array_step.setObjectName(_fromUtf8("array_step"))
        self.gridLayout_2.addWidget(self.array_step, 0, 1, 1, 1)
        self.rout_x = QtGui.QLineEdit(self.layoutWidget)
        self.rout_x.setMinimumSize(QtCore.QSize(68, 25))
        self.rout_x.setMaximumSize(QtCore.QSize(68, 25))
        self.rout_x.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.rout_x.setObjectName(_fromUtf8("rout_x"))
        self.gridLayout_2.addWidget(self.rout_x, 0, 7, 1, 1)
        self.label_board_thick = QtGui.QLabel(self.layoutWidget)
        self.label_board_thick.setMinimumSize(QtCore.QSize(100, 25))
        self.label_board_thick.setMaximumSize(QtCore.QSize(100, 25))
        self.label_board_thick.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_board_thick.setObjectName(_fromUtf8("label_board_thick"))
        self.gridLayout_2.addWidget(self.label_board_thick, 1, 0, 1, 1)
        self.label_array_step = QtGui.QLabel(self.layoutWidget)
        self.label_array_step.setMinimumSize(QtCore.QSize(100, 25))
        self.label_array_step.setMaximumSize(QtCore.QSize(100, 25))
        self.label_array_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_array_step.setObjectName(_fromUtf8("label_array_step"))
        self.gridLayout_2.addWidget(self.label_array_step, 0, 0, 1, 1)
        self.array_x_size = QtGui.QLineEdit(self.layoutWidget)
        self.array_x_size.setEnabled(False)
        self.array_x_size.setMinimumSize(QtCore.QSize(68, 25))
        self.array_x_size.setMaximumSize(QtCore.QSize(68, 25))
        self.array_x_size.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.array_x_size.setText(_fromUtf8(""))
        self.array_x_size.setMaxLength(7)
        self.array_x_size.setObjectName(_fromUtf8("array_x_size"))
        self.gridLayout_2.addWidget(self.array_x_size, 0, 3, 1, 1)
        self.label_split_pth = QtGui.QLabel(self.layoutWidget)
        self.label_split_pth.setMinimumSize(QtCore.QSize(0, 25))
        self.label_split_pth.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_split_pth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_split_pth.setObjectName(_fromUtf8("label_split_pth"))
        self.gridLayout_2.addWidget(self.label_split_pth, 2, 2, 1, 1)
        self.split_pth = QtGui.QLineEdit(self.layoutWidget)
        self.split_pth.setMinimumSize(QtCore.QSize(68, 25))
        self.split_pth.setMaximumSize(QtCore.QSize(68, 25))
        self.split_pth.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.split_pth.setObjectName(_fromUtf8("split_pth"))
        self.gridLayout_2.addWidget(self.split_pth, 2, 3, 1, 1)
        self.label_dry_hole = QtGui.QLabel(self.layoutWidget)
        self.label_dry_hole.setMinimumSize(QtCore.QSize(100, 25))
        self.label_dry_hole.setMaximumSize(QtCore.QSize(100, 25))
        self.label_dry_hole.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dry_hole.setObjectName(_fromUtf8("label_dry_hole"))
        self.gridLayout_2.addWidget(self.label_dry_hole, 2, 4, 1, 1)
        self.rout_y = QtGui.QLineEdit(self.layoutWidget)
        self.rout_y.setMinimumSize(QtCore.QSize(68, 25))
        self.rout_y.setMaximumSize(QtCore.QSize(68, 25))
        self.rout_y.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.rout_y.setObjectName(_fromUtf8("rout_y"))
        self.gridLayout_2.addWidget(self.rout_y, 1, 7, 1, 1)
        self.board_thick = QtGui.QLineEdit(self.layoutWidget)
        self.board_thick.setMinimumSize(QtCore.QSize(68, 25))
        self.board_thick.setMaximumSize(QtCore.QSize(68, 25))
        self.board_thick.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.board_thick.setText(_fromUtf8(""))
        self.board_thick.setObjectName(_fromUtf8("board_thick"))
        self.gridLayout_2.addWidget(self.board_thick, 1, 1, 1, 1)
        self.label_rout_y = QtGui.QLabel(self.layoutWidget)
        self.label_rout_y.setMinimumSize(QtCore.QSize(100, 25))
        self.label_rout_y.setMaximumSize(QtCore.QSize(100, 25))
        self.label_rout_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rout_y.setObjectName(_fromUtf8("label_rout_y"))
        self.gridLayout_2.addWidget(self.label_rout_y, 1, 6, 1, 1)
        self.panel_y = QtGui.QLineEdit(self.layoutWidget)
        self.panel_y.setMinimumSize(QtCore.QSize(68, 25))
        self.panel_y.setMaximumSize(QtCore.QSize(68, 25))
        self.panel_y.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.panel_y.setObjectName(_fromUtf8("panel_y"))
        self.gridLayout_2.addWidget(self.panel_y, 1, 5, 1, 1)
        self.label_panel_y = QtGui.QLabel(self.layoutWidget)
        self.label_panel_y.setMinimumSize(QtCore.QSize(100, 25))
        self.label_panel_y.setMaximumSize(QtCore.QSize(100, 25))
        self.label_panel_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_panel_y.setObjectName(_fromUtf8("label_panel_y"))
        self.gridLayout_2.addWidget(self.label_panel_y, 1, 4, 1, 1)
        self.label_split_via = QtGui.QLabel(self.layoutWidget)
        self.label_split_via.setMinimumSize(QtCore.QSize(100, 25))
        self.label_split_via.setMaximumSize(QtCore.QSize(100, 25))
        self.label_split_via.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_split_via.setObjectName(_fromUtf8("label_split_via"))
        self.gridLayout_2.addWidget(self.label_split_via, 2, 0, 1, 1)
        self.label_array_y_size = QtGui.QLabel(self.layoutWidget)
        self.label_array_y_size.setMinimumSize(QtCore.QSize(0, 25))
        self.label_array_y_size.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_array_y_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_array_y_size.setObjectName(_fromUtf8("label_array_y_size"))
        self.gridLayout_2.addWidget(self.label_array_y_size, 1, 2, 1, 1)
        self.split_via = QtGui.QLineEdit(self.layoutWidget)
        self.split_via.setMinimumSize(QtCore.QSize(68, 25))
        self.split_via.setMaximumSize(QtCore.QSize(68, 25))
        self.split_via.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.split_via.setText(_fromUtf8(""))
        self.split_via.setObjectName(_fromUtf8("split_via"))
        self.gridLayout_2.addWidget(self.split_via, 2, 1, 1, 1)
        self.dry_hole = QtGui.QLineEdit(self.layoutWidget)
        self.dry_hole.setMinimumSize(QtCore.QSize(68, 25))
        self.dry_hole.setMaximumSize(QtCore.QSize(68, 25))
        self.dry_hole.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.dry_hole.setText(_fromUtf8(""))
        self.dry_hole.setObjectName(_fromUtf8("dry_hole"))
        self.gridLayout_2.addWidget(self.dry_hole, 2, 5, 1, 1)
        self.array_y_size = QtGui.QLineEdit(self.layoutWidget)
        self.array_y_size.setEnabled(False)
        self.array_y_size.setMinimumSize(QtCore.QSize(68, 25))
        self.array_y_size.setMaximumSize(QtCore.QSize(68, 25))
        self.array_y_size.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.array_y_size.setMaxLength(7)
        self.array_y_size.setObjectName(_fromUtf8("array_y_size"))
        self.gridLayout_2.addWidget(self.array_y_size, 1, 3, 1, 1)
        self.label_panel = QtGui.QLabel(self.layoutWidget)
        self.label_panel.setMinimumSize(QtCore.QSize(100, 25))
        self.label_panel.setMaximumSize(QtCore.QSize(100, 25))
        self.label_panel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_panel.setObjectName(_fromUtf8("label_panel"))
        self.gridLayout_2.addWidget(self.label_panel, 2, 6, 1, 1)
        self.panel = QtGui.QLineEdit(self.layoutWidget)
        self.panel.setMinimumSize(QtCore.QSize(68, 25))
        self.panel.setMaximumSize(QtCore.QSize(68, 25))
        self.panel.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.panel.setReadOnly(True)
        self.panel.setObjectName(_fromUtf8("panel"))
        self.gridLayout_2.addWidget(self.panel, 2, 7, 1, 1)
        self.line_13 = QtGui.QFrame(self.array_parm_box)
        self.line_13.setGeometry(QtCore.QRect(120, 1, 703, 10))
        self.line_13.setFrameShadow(QtGui.QFrame.Raised)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout.addWidget(self.array_parm_box)
        self.select_parm_box = QtGui.QGroupBox(Form)
        self.select_parm_box.setMinimumSize(QtCore.QSize(0, 190))
        self.select_parm_box.setObjectName(_fromUtf8("select_parm_box"))
        self.line_14 = QtGui.QFrame(self.select_parm_box)
        self.line_14.setGeometry(QtCore.QRect(110, 1, 712, 10))
        self.line_14.setFrameShadow(QtGui.QFrame.Raised)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.layoutWidget1 = QtGui.QWidget(self.select_parm_box)
        self.layoutWidget1.setGeometry(QtCore.QRect(13, 21, 261, 27))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_sh_site = QtGui.QLabel(self.layoutWidget1)
        self.label_sh_site.setMinimumSize(QtCore.QSize(72, 25))
        self.label_sh_site.setMaximumSize(QtCore.QSize(72, 25))
        self.label_sh_site.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sh_site.setObjectName(_fromUtf8("label_sh_site"))
        self.horizontalLayout_2.addWidget(self.label_sh_site)
        self.sh_site = QtGui.QComboBox(self.layoutWidget1)
        self.sh_site.setMinimumSize(QtCore.QSize(100, 25))
        self.sh_site.setMaximumSize(QtCore.QSize(100, 25))
        self.sh_site.setStyleSheet(_fromUtf8("font: 10pt \"Agency FB\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.sh_site.setObjectName(_fromUtf8("sh_site"))
        self.sh_site.addItem(_fromUtf8(""))
        self.sh_site.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.sh_site)
        self.flow_content = QtGui.QLabel(self.layoutWidget1)
        self.flow_content.setMaximumSize(QtCore.QSize(75, 25))
        self.flow_content.setObjectName(_fromUtf8("flow_content"))
        self.horizontalLayout_2.addWidget(self.flow_content)
        self.layoutWidget2 = QtGui.QWidget(self.select_parm_box)
        self.layoutWidget2.setGeometry(QtCore.QRect(600, 20, 188, 34))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_sel_socket = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_sel_socket.sizePolicy().hasHeightForWidth())
        self.label_sel_socket.setSizePolicy(sizePolicy)
        self.label_sel_socket.setMaximumSize(QtCore.QSize(108, 32))
        self.label_sel_socket.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sel_socket.setObjectName(_fromUtf8("label_sel_socket"))
        self.horizontalLayout_10.addWidget(self.label_sel_socket)
        self.sel_socket_no = QtGui.QRadioButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sel_socket_no.sizePolicy().hasHeightForWidth())
        self.sel_socket_no.setSizePolicy(sizePolicy)
        self.sel_socket_no.setMinimumSize(QtCore.QSize(50, 32))
        self.sel_socket_no.setMaximumSize(QtCore.QSize(80, 32))
        self.sel_socket_no.setChecked(True)
        self.sel_socket_no.setObjectName(_fromUtf8("sel_socket_no"))
        self.btnGrp_sel_socket = QtGui.QButtonGroup(Form)
        self.btnGrp_sel_socket.setObjectName(_fromUtf8("btnGrp_sel_socket"))
        self.btnGrp_sel_socket.addButton(self.sel_socket_no)
        self.horizontalLayout_10.addWidget(self.sel_socket_no)
        self.sel_socket_yes = QtGui.QRadioButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sel_socket_yes.sizePolicy().hasHeightForWidth())
        self.sel_socket_yes.setSizePolicy(sizePolicy)
        self.sel_socket_yes.setMinimumSize(QtCore.QSize(50, 32))
        self.sel_socket_yes.setMaximumSize(QtCore.QSize(80, 32))
        self.sel_socket_yes.setObjectName(_fromUtf8("sel_socket_yes"))
        self.btnGrp_sel_socket.addButton(self.sel_socket_yes)
        self.horizontalLayout_10.addWidget(self.sel_socket_yes)
        self.layoutWidget3 = QtGui.QWidget(self.select_parm_box)
        self.layoutWidget3.setGeometry(QtCore.QRect(331, 21, 231, 34))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_cycle_in = QtGui.QLabel(self.layoutWidget3)
        self.label_cycle_in.setMinimumSize(QtCore.QSize(70, 32))
        self.label_cycle_in.setMaximumSize(QtCore.QSize(70, 32))
        self.label_cycle_in.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cycle_in.setObjectName(_fromUtf8("label_cycle_in"))
        self.horizontalLayout_3.addWidget(self.label_cycle_in)
        self.cycle_in_silk = QtGui.QCheckBox(self.layoutWidget3)
        self.cycle_in_silk.setObjectName(_fromUtf8("cycle_in_silk"))
        self.horizontalLayout_3.addWidget(self.cycle_in_silk)
        self.cycle_in_sm = QtGui.QCheckBox(self.layoutWidget3)
        self.cycle_in_sm.setObjectName(_fromUtf8("cycle_in_sm"))
        self.horizontalLayout_3.addWidget(self.cycle_in_sm)
        self.cycle_in_signal = QtGui.QCheckBox(self.layoutWidget3)
        self.cycle_in_signal.setObjectName(_fromUtf8("cycle_in_signal"))
        self.horizontalLayout_3.addWidget(self.cycle_in_signal)
        self.layoutWidget4 = QtGui.QWidget(self.select_parm_box)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 50, 800, 114))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_add_ld_symbol = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_add_ld_symbol.sizePolicy().hasHeightForWidth())
        self.label_add_ld_symbol.setSizePolicy(sizePolicy)
        self.label_add_ld_symbol.setMaximumSize(QtCore.QSize(72, 32))
        self.label_add_ld_symbol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_add_ld_symbol.setObjectName(_fromUtf8("label_add_ld_symbol"))
        self.gridLayout_3.addWidget(self.label_add_ld_symbol, 1, 0, 1, 1)
        self.add_ld_symbol_no = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_ld_symbol_no.sizePolicy().hasHeightForWidth())
        self.add_ld_symbol_no.setSizePolicy(sizePolicy)
        self.add_ld_symbol_no.setMinimumSize(QtCore.QSize(45, 32))
        self.add_ld_symbol_no.setMaximumSize(QtCore.QSize(45, 32))
        self.add_ld_symbol_no.setChecked(True)
        self.add_ld_symbol_no.setObjectName(_fromUtf8("add_ld_symbol_no"))
        self.btnGrp_add_ld_symbol = QtGui.QButtonGroup(Form)
        self.btnGrp_add_ld_symbol.setObjectName(_fromUtf8("btnGrp_add_ld_symbol"))
        self.btnGrp_add_ld_symbol.addButton(self.add_ld_symbol_no)
        self.gridLayout_3.addWidget(self.add_ld_symbol_no, 1, 1, 1, 1)
        self.add_ld_symbol_yes = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_ld_symbol_yes.sizePolicy().hasHeightForWidth())
        self.add_ld_symbol_yes.setSizePolicy(sizePolicy)
        self.add_ld_symbol_yes.setMinimumSize(QtCore.QSize(45, 32))
        self.add_ld_symbol_yes.setMaximumSize(QtCore.QSize(45, 32))
        self.add_ld_symbol_yes.setObjectName(_fromUtf8("add_ld_symbol_yes"))
        self.btnGrp_add_ld_symbol.addButton(self.add_ld_symbol_yes)
        self.gridLayout_3.addWidget(self.add_ld_symbol_yes, 1, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget4)
        self.line_2.setFrameShadow(QtGui.QFrame.Raised)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 1, 3, 1, 1)
        self.label_sel_vut = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_sel_vut.sizePolicy().hasHeightForWidth())
        self.label_sel_vut.setSizePolicy(sizePolicy)
        self.label_sel_vut.setMaximumSize(QtCore.QSize(72, 32))
        self.label_sel_vut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sel_vut.setObjectName(_fromUtf8("label_sel_vut"))
        self.gridLayout_3.addWidget(self.label_sel_vut, 1, 4, 1, 1)
        self.sel_vut_no = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sel_vut_no.sizePolicy().hasHeightForWidth())
        self.sel_vut_no.setSizePolicy(sizePolicy)
        self.sel_vut_no.setMinimumSize(QtCore.QSize(45, 32))
        self.sel_vut_no.setMaximumSize(QtCore.QSize(45, 32))
        self.sel_vut_no.setChecked(True)
        self.sel_vut_no.setObjectName(_fromUtf8("sel_vut_no"))
        self.btnGrp_sel_vut = QtGui.QButtonGroup(Form)
        self.btnGrp_sel_vut.setObjectName(_fromUtf8("btnGrp_sel_vut"))
        self.btnGrp_sel_vut.addButton(self.sel_vut_no)
        self.gridLayout_3.addWidget(self.sel_vut_no, 1, 5, 1, 1)
        self.sel_vut_yes = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sel_vut_yes.sizePolicy().hasHeightForWidth())
        self.sel_vut_yes.setSizePolicy(sizePolicy)
        self.sel_vut_yes.setMinimumSize(QtCore.QSize(45, 32))
        self.sel_vut_yes.setMaximumSize(QtCore.QSize(50, 32))
        self.sel_vut_yes.setObjectName(_fromUtf8("sel_vut_yes"))
        self.btnGrp_sel_vut.addButton(self.sel_vut_yes)
        self.gridLayout_3.addWidget(self.sel_vut_yes, 1, 6, 1, 1)
        self.line_5 = QtGui.QFrame(self.layoutWidget4)
        self.line_5.setFrameShadow(QtGui.QFrame.Raised)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_3.addWidget(self.line_5, 1, 7, 1, 1)
        self.label_add_eagle_panel = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_add_eagle_panel.sizePolicy().hasHeightForWidth())
        self.label_add_eagle_panel.setSizePolicy(sizePolicy)
        self.label_add_eagle_panel.setMaximumSize(QtCore.QSize(72, 32))
        self.label_add_eagle_panel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_add_eagle_panel.setObjectName(_fromUtf8("label_add_eagle_panel"))
        self.gridLayout_3.addWidget(self.label_add_eagle_panel, 1, 8, 1, 1)
        self.add_eagle_panel_no = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.add_eagle_panel_no.sizePolicy().hasHeightForWidth())
        self.add_eagle_panel_no.setSizePolicy(sizePolicy)
        self.add_eagle_panel_no.setMinimumSize(QtCore.QSize(45, 32))
        self.add_eagle_panel_no.setMaximumSize(QtCore.QSize(45, 32))
        self.add_eagle_panel_no.setChecked(True)
        self.add_eagle_panel_no.setObjectName(_fromUtf8("add_eagle_panel_no"))
        self.btnGrp_add_eagle_panel = QtGui.QButtonGroup(Form)
        self.btnGrp_add_eagle_panel.setObjectName(_fromUtf8("btnGrp_add_eagle_panel"))
        self.btnGrp_add_eagle_panel.addButton(self.add_eagle_panel_no)
        self.gridLayout_3.addWidget(self.add_eagle_panel_no, 1, 9, 1, 1)
        self.add_eagle_panel_yes = QtGui.QRadioButton(self.layoutWidget4)
        self.add_eagle_panel_yes.setMinimumSize(QtCore.QSize(45, 32))
        self.add_eagle_panel_yes.setMaximumSize(QtCore.QSize(45, 32))
        self.add_eagle_panel_yes.setObjectName(_fromUtf8("add_eagle_panel_yes"))
        self.btnGrp_add_eagle_panel.addButton(self.add_eagle_panel_yes)
        self.gridLayout_3.addWidget(self.add_eagle_panel_yes, 1, 10, 1, 1)
        self.line_8 = QtGui.QFrame(self.layoutWidget4)
        self.line_8.setFrameShadow(QtGui.QFrame.Raised)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_3.addWidget(self.line_8, 1, 11, 1, 1)
        self.sel_mid_rout_short = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sel_mid_rout_short.sizePolicy().hasHeightForWidth())
        self.sel_mid_rout_short.setSizePolicy(sizePolicy)
        self.sel_mid_rout_short.setMinimumSize(QtCore.QSize(50, 32))
        self.sel_mid_rout_short.setMaximumSize(QtCore.QSize(50, 32))
        self.sel_mid_rout_short.setChecked(True)
        self.sel_mid_rout_short.setObjectName(_fromUtf8("sel_mid_rout_short"))
        self.btnGrp_sel_mid_rout = QtGui.QButtonGroup(Form)
        self.btnGrp_sel_mid_rout.setObjectName(_fromUtf8("btnGrp_sel_mid_rout"))
        self.btnGrp_sel_mid_rout.addButton(self.sel_mid_rout_short)
        self.gridLayout_3.addWidget(self.sel_mid_rout_short, 1, 13, 1, 1)
        self.sel_mid_rout_long = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sel_mid_rout_long.sizePolicy().hasHeightForWidth())
        self.sel_mid_rout_long.setSizePolicy(sizePolicy)
        self.sel_mid_rout_long.setMinimumSize(QtCore.QSize(50, 32))
        self.sel_mid_rout_long.setMaximumSize(QtCore.QSize(50, 32))
        self.sel_mid_rout_long.setObjectName(_fromUtf8("sel_mid_rout_long"))
        self.btnGrp_sel_mid_rout.addButton(self.sel_mid_rout_long)
        self.gridLayout_3.addWidget(self.sel_mid_rout_long, 1, 14, 1, 1)
        self.label_wei_xiang = QtGui.QLabel(self.layoutWidget4)
        self.label_wei_xiang.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_wei_xiang.setObjectName(_fromUtf8("label_wei_xiang"))
        self.gridLayout_3.addWidget(self.label_wei_xiang, 2, 0, 1, 1)
        self.wei_xiang = QtGui.QComboBox(self.layoutWidget4)
        self.wei_xiang.setMinimumSize(QtCore.QSize(80, 30))
        self.wei_xiang.setMaximumSize(QtCore.QSize(180, 32))
        self.wei_xiang.setStyleSheet(_fromUtf8("font: 10pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:3px;"))
        self.wei_xiang.setObjectName(_fromUtf8("wei_xiang"))
        self.wei_xiang.addItem(_fromUtf8(""))
        self.wei_xiang.addItem(_fromUtf8(""))
        self.wei_xiang.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.wei_xiang, 2, 1, 1, 2)
        self.line_3 = QtGui.QFrame(self.layoutWidget4)
        self.line_3.setFrameShadow(QtGui.QFrame.Raised)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 2, 3, 1, 1)
        self.label_select_color_silk = QtGui.QLabel(self.layoutWidget4)
        self.label_select_color_silk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_select_color_silk.setObjectName(_fromUtf8("label_select_color_silk"))
        self.gridLayout_3.addWidget(self.label_select_color_silk, 2, 4, 1, 1)
        self.select_color_silk = QtGui.QComboBox(self.layoutWidget4)
        self.select_color_silk.setMinimumSize(QtCore.QSize(80, 30))
        self.select_color_silk.setMaximumSize(QtCore.QSize(180, 32))
        self.select_color_silk.setStyleSheet(_fromUtf8("font: 10pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:3px;"))
        self.select_color_silk.setObjectName(_fromUtf8("select_color_silk"))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))
        self.select_color_silk.addItem(_fromUtf8(""))        
        self.gridLayout_3.addWidget(self.select_color_silk, 2, 5, 1, 2)
        self.line_6 = QtGui.QFrame(self.layoutWidget4)
        self.line_6.setFrameShadow(QtGui.QFrame.Raised)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_3.addWidget(self.line_6, 2, 7, 1, 1)
        self.label_select_silk_times = QtGui.QLabel(self.layoutWidget4)
        self.label_select_silk_times.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_select_silk_times.setObjectName(_fromUtf8("label_select_silk_times"))
        self.gridLayout_3.addWidget(self.label_select_silk_times, 2, 8, 1, 1)
        self.select_silk_times = QtGui.QComboBox(self.layoutWidget4)
        self.select_silk_times.setMinimumSize(QtCore.QSize(80, 30))
        self.select_silk_times.setMaximumSize(QtCore.QSize(180, 32))
        self.select_silk_times.setStyleSheet(_fromUtf8("font: 10pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:3px;"))
        self.select_silk_times.setObjectName(_fromUtf8("select_silk_times"))
        self.select_silk_times.addItem(_fromUtf8(""))
        self.select_silk_times.addItem(_fromUtf8(""))
        self.select_silk_times.addItem(_fromUtf8(""))
        self.select_silk_times.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.select_silk_times, 2, 9, 1, 2)
        self.label_select_solder_times = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_select_solder_times.sizePolicy().hasHeightForWidth())
        self.label_select_solder_times.setSizePolicy(sizePolicy)
        self.label_select_solder_times.setMinimumSize(QtCore.QSize(120, 0))
        self.label_select_solder_times.setMaximumSize(QtCore.QSize(120, 32))
        self.label_select_solder_times.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_select_solder_times.setObjectName(_fromUtf8("label_select_solder_times"))
        self.gridLayout_3.addWidget(self.label_select_solder_times, 2, 12, 1, 1)
        self.select_solder_times = QtGui.QComboBox(self.layoutWidget4)
        self.select_solder_times.setMinimumSize(QtCore.QSize(80, 30))
        self.select_solder_times.setMaximumSize(QtCore.QSize(180, 32))
        self.select_solder_times.setStyleSheet(_fromUtf8("font: 10pt \"Agency FB\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:3px;"))
        self.select_solder_times.setObjectName(_fromUtf8("select_solder_times"))
        self.select_solder_times.addItem(_fromUtf8(""))
        self.select_solder_times.addItem(_fromUtf8(""))
        self.select_solder_times.addItem(_fromUtf8(""))
        self.select_solder_times.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.select_solder_times, 2, 13, 1, 2)
        self.label_sel_mid_rout = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_sel_mid_rout.sizePolicy().hasHeightForWidth())
        self.label_sel_mid_rout.setSizePolicy(sizePolicy)
        self.label_sel_mid_rout.setMinimumSize(QtCore.QSize(120, 32))
        self.label_sel_mid_rout.setMaximumSize(QtCore.QSize(120, 32))
        self.label_sel_mid_rout.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sel_mid_rout.setObjectName(_fromUtf8("label_sel_mid_rout"))
        self.gridLayout_3.addWidget(self.label_sel_mid_rout, 1, 12, 1, 1)
        self.label_sel_finger = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_sel_finger.sizePolicy().hasHeightForWidth())
        self.label_sel_finger.setSizePolicy(sizePolicy)
        self.label_sel_finger.setMaximumSize(QtCore.QSize(72, 32))
        self.label_sel_finger.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sel_finger.setObjectName(_fromUtf8("label_sel_finger"))
        self.gridLayout_3.addWidget(self.label_sel_finger, 0, 8, 1, 1)
        self.label_if_jsz = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_if_jsz.sizePolicy().hasHeightForWidth())
        self.label_if_jsz.setSizePolicy(sizePolicy)
        self.label_if_jsz.setMinimumSize(QtCore.QSize(72, 0))
        self.label_if_jsz.setMaximumSize(QtCore.QSize(72, 32))
        self.label_if_jsz.setObjectName(_fromUtf8("label_if_jsz"))
        self.gridLayout_3.addWidget(self.label_if_jsz, 0, 0, 1, 1)
        self.sel_jsz_no = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sel_jsz_no.sizePolicy().hasHeightForWidth())
        self.sel_jsz_no.setSizePolicy(sizePolicy)
        self.sel_jsz_no.setMinimumSize(QtCore.QSize(45, 32))
        self.sel_jsz_no.setMaximumSize(QtCore.QSize(45, 32))
        self.sel_jsz_no.setChecked(True)
        self.sel_jsz_no.setObjectName(_fromUtf8("sel_jsz_no"))
        self.btnGrp_if_jsz_select = QtGui.QButtonGroup(Form)
        self.btnGrp_if_jsz_select.setObjectName(_fromUtf8("btnGrp_if_jsz_select"))
        self.btnGrp_if_jsz_select.addButton(self.sel_jsz_no)
        self.gridLayout_3.addWidget(self.sel_jsz_no, 0, 1, 1, 1)
        self.sel_jsz_yes = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sel_jsz_yes.sizePolicy().hasHeightForWidth())
        self.sel_jsz_yes.setSizePolicy(sizePolicy)
        self.sel_jsz_yes.setMinimumSize(QtCore.QSize(45, 32))
        self.sel_jsz_yes.setMaximumSize(QtCore.QSize(45, 32))
        self.sel_jsz_yes.setObjectName(_fromUtf8("sel_jsz_yes"))
        self.btnGrp_if_jsz_select.addButton(self.sel_jsz_yes)
        self.gridLayout_3.addWidget(self.sel_jsz_yes, 0, 2, 1, 1)
        self.label_add_hj_panel = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_add_hj_panel.sizePolicy().hasHeightForWidth())
        self.label_add_hj_panel.setSizePolicy(sizePolicy)
        self.label_add_hj_panel.setMaximumSize(QtCore.QSize(72, 32))
        self.label_add_hj_panel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_add_hj_panel.setObjectName(_fromUtf8("label_add_hj_panel"))
        self.gridLayout_3.addWidget(self.label_add_hj_panel, 0, 4, 1, 1)
        self.add_hj_panel_no = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.add_hj_panel_no.sizePolicy().hasHeightForWidth())
        self.add_hj_panel_no.setSizePolicy(sizePolicy)
        self.add_hj_panel_no.setMinimumSize(QtCore.QSize(45, 32))
        self.add_hj_panel_no.setMaximumSize(QtCore.QSize(45, 32))
        self.add_hj_panel_no.setChecked(True)
        self.add_hj_panel_no.setObjectName(_fromUtf8("add_hj_panel_no"))
        self.btnGrp_add_hj_panel = QtGui.QButtonGroup(Form)
        self.btnGrp_add_hj_panel.setObjectName(_fromUtf8("btnGrp_add_hj_panel"))
        self.btnGrp_add_hj_panel.addButton(self.add_hj_panel_no)
        self.gridLayout_3.addWidget(self.add_hj_panel_no, 0, 5, 1, 1)
        self.add_hj_panel_yes = QtGui.QRadioButton(self.layoutWidget4)
        self.add_hj_panel_yes.setMinimumSize(QtCore.QSize(45, 32))
        self.add_hj_panel_yes.setMaximumSize(QtCore.QSize(45, 32))
        self.add_hj_panel_yes.setObjectName(_fromUtf8("add_hj_panel_yes"))
        self.btnGrp_add_hj_panel.addButton(self.add_hj_panel_yes)
        self.gridLayout_3.addWidget(self.add_hj_panel_yes, 0, 6, 1, 1)
        self.sel_finger_no = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sel_finger_no.sizePolicy().hasHeightForWidth())
        self.sel_finger_no.setSizePolicy(sizePolicy)
        self.sel_finger_no.setMinimumSize(QtCore.QSize(45, 32))
        self.sel_finger_no.setMaximumSize(QtCore.QSize(45, 32))
        self.sel_finger_no.setChecked(True)
        self.sel_finger_no.setObjectName(_fromUtf8("sel_finger_no"))
        self.btnGrp_sel_finger = QtGui.QButtonGroup(Form)
        self.btnGrp_sel_finger.setObjectName(_fromUtf8("btnGrp_sel_finger"))
        self.btnGrp_sel_finger.addButton(self.sel_finger_no)
        self.gridLayout_3.addWidget(self.sel_finger_no, 0, 9, 1, 1)
        self.sel_finger_yes = QtGui.QRadioButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sel_finger_yes.sizePolicy().hasHeightForWidth())
        self.sel_finger_yes.setSizePolicy(sizePolicy)
        self.sel_finger_yes.setMinimumSize(QtCore.QSize(45, 32))
        self.sel_finger_yes.setMaximumSize(QtCore.QSize(45, 32))
        self.sel_finger_yes.setObjectName(_fromUtf8("sel_finger_yes"))
        self.btnGrp_sel_finger.addButton(self.sel_finger_yes)
        self.gridLayout_3.addWidget(self.sel_finger_yes, 0, 10, 1, 1)
        self.label_g_direction = QtGui.QLabel(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_g_direction.sizePolicy().hasHeightForWidth())
        self.label_g_direction.setSizePolicy(sizePolicy)
        self.label_g_direction.setMinimumSize(QtCore.QSize(120, 32))
        self.label_g_direction.setMaximumSize(QtCore.QSize(120, 32))
        self.label_g_direction.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_g_direction.setObjectName(_fromUtf8("label_g_direction"))
        self.gridLayout_3.addWidget(self.label_g_direction, 0, 12, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget4)
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 0, 3, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget4)
        self.line_7.setFrameShadow(QtGui.QFrame.Raised)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_3.addWidget(self.line_7, 0, 11, 1, 1)
        self.g_direction = QtGui.QComboBox(self.layoutWidget4)
        self.g_direction.setEnabled(False)
        self.g_direction.setMinimumSize(QtCore.QSize(80, 30))
        self.g_direction.setMaximumSize(QtCore.QSize(160, 25))
        self.g_direction.setStyleSheet(_fromUtf8("font: 10pt \"Abyssinisa SIL\";\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:3px;"))
        # self.g_direction.setInputMethodHints(QtCore.Qt.ImhNone)
        self.g_direction.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.g_direction.setObjectName(_fromUtf8("g_direction"))
        self.g_direction.addItem(_fromUtf8(""))
        self.g_direction.addItem(_fromUtf8(""))
        self.g_direction.addItem(_fromUtf8(""))
        self.g_direction.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.g_direction, 0, 13, 1, 2)
        self.line_4 = QtGui.QFrame(self.layoutWidget4)
        self.line_4.setFrameShadow(QtGui.QFrame.Raised)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_3.addWidget(self.line_4, 0, 7, 1, 1)
        self.line_9 = QtGui.QFrame(self.layoutWidget4)
        self.line_9.setFrameShadow(QtGui.QFrame.Raised)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_3.addWidget(self.line_9, 2, 11, 1, 1)
        self.verticalLayout.addWidget(self.select_parm_box)
        self.mao_ding_parm_box = QtGui.QGroupBox(Form)
        self.mao_ding_parm_box.setMinimumSize(QtCore.QSize(0, 61))
        self.mao_ding_parm_box.setObjectName(_fromUtf8("mao_ding_parm_box"))
        self.layoutWidget5 = QtGui.QWidget(self.mao_ding_parm_box)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 388, 32))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.mao_pin_x = QtGui.QLineEdit(self.layoutWidget5)
        self.mao_pin_x.setMinimumSize(QtCore.QSize(60, 25))
        self.mao_pin_x.setMaximumSize(QtCore.QSize(60, 25))
        self.mao_pin_x.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.mao_pin_x.setObjectName(_fromUtf8("mao_pin_x"))
        self.gridLayout_4.addWidget(self.mao_pin_x, 0, 1, 1, 1)
        self.mao_pin_y = QtGui.QLineEdit(self.layoutWidget5)
        self.mao_pin_y.setMinimumSize(QtCore.QSize(60, 25))
        self.mao_pin_y.setMaximumSize(QtCore.QSize(60, 25))
        self.mao_pin_y.setStyleSheet(_fromUtf8("font: 11pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:3px;"))
        self.mao_pin_y.setObjectName(_fromUtf8("mao_pin_y"))
        self.gridLayout_4.addWidget(self.mao_pin_y, 0, 3, 1, 1)
        self.ape3000_base = QtGui.QComboBox(self.layoutWidget5)
        self.ape3000_base.setMinimumSize(QtCore.QSize(80, 30))
        self.ape3000_base.setMaximumSize(QtCore.QSize(180, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ape3000_base.setFont(font)
        self.ape3000_base.setStyleSheet(_fromUtf8("font: 10pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:3px;"))
        self.ape3000_base.setObjectName(_fromUtf8("ape3000_base"))
        self.ape3000_base.addItem(_fromUtf8(""))
        self.ape3000_base.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.ape3000_base, 0, 5, 1, 1)
        self.label_ape3000_base = QtGui.QLabel(self.layoutWidget5)
        self.label_ape3000_base.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ape3000_base.setObjectName(_fromUtf8("label_ape3000_base"))
        self.gridLayout_4.addWidget(self.label_ape3000_base, 0, 4, 1, 1)
        self.label_mao_pin_y = QtGui.QLabel(self.layoutWidget5)
        self.label_mao_pin_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mao_pin_y.setObjectName(_fromUtf8("label_mao_pin_y"))
        self.gridLayout_4.addWidget(self.label_mao_pin_y, 0, 2, 1, 1)
        self.label_mao_pin_x = QtGui.QLabel(self.layoutWidget5)
        self.label_mao_pin_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mao_pin_x.setObjectName(_fromUtf8("label_mao_pin_x"))
        self.gridLayout_4.addWidget(self.label_mao_pin_x, 0, 0, 1, 1)
        self.line_15 = QtGui.QFrame(self.mao_ding_parm_box)
        self.line_15.setGeometry(QtCore.QRect(120, 1, 703, 10))
        self.line_15.setFrameShadow(QtGui.QFrame.Raised)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.pin_lam_mode = QtGui.QCheckBox(self.mao_ding_parm_box)
        self.pin_lam_mode.setGeometry(QtCore.QRect(430, 30, 100, 16))
        self.pin_lam_mode.setObjectName(_fromUtf8("pin_lam_mode"))
        self.verticalLayout.addWidget(self.mao_ding_parm_box)
        self.lamin_parm_box = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lamin_parm_box.sizePolicy().hasHeightForWidth())
        self.lamin_parm_box.setSizePolicy(sizePolicy)
        self.lamin_parm_box.setMinimumSize(QtCore.QSize(0, 150))
        self.lamin_parm_box.setMaximumSize(QtCore.QSize(2000, 160))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.lamin_parm_box.setFont(font)
        self.lamin_parm_box.setObjectName(_fromUtf8("lamin_parm_box"))
        self.gridLayout_5 = QtGui.QGridLayout(self.lamin_parm_box)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tableWidget_lamin = QtGui.QTableWidget(self.lamin_parm_box)
        self.tableWidget_lamin.setEnabled(True)
        self.tableWidget_lamin.setMouseTracking(False)
        self.tableWidget_lamin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableWidget_lamin.setToolTip(_fromUtf8(""))
        self.tableWidget_lamin.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget_lamin.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget_lamin.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_lamin.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tableWidget_lamin.setShowGrid(True)
        self.tableWidget_lamin.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_lamin.setWordWrap(True)
        self.tableWidget_lamin.setCornerButtonEnabled(True)
        self.tableWidget_lamin.setRowCount(3)
        self.tableWidget_lamin.setColumnCount(14)
        self.tableWidget_lamin.setObjectName(_fromUtf8("tableWidget_lamin"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_lamin.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_lamin.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_lamin.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_lamin.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_lamin.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_lamin.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_lamin.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_lamin.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_lamin.setItem(2, 2, item)
        self.tableWidget_lamin.horizontalHeader().setVisible(True)
        self.tableWidget_lamin.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_lamin.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget_lamin.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_lamin.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_lamin.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_lamin.verticalHeader().setVisible(False)
        self.tableWidget_lamin.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_lamin.verticalHeader().setDefaultSectionSize(33)
        self.tableWidget_lamin.verticalHeader().setHighlightSections(True)
        self.tableWidget_lamin.verticalHeader().setMinimumSectionSize(22)
        self.tableWidget_lamin.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_lamin.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tableWidget_lamin, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.lamin_parm_box)
        self.copper_parm_box = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copper_parm_box.sizePolicy().hasHeightForWidth())
        self.copper_parm_box.setSizePolicy(sizePolicy)
        self.copper_parm_box.setMinimumSize(QtCore.QSize(0, 150))
        self.copper_parm_box.setMaximumSize(QtCore.QSize(20000, 3000))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.copper_parm_box.setFont(font)
        self.copper_parm_box.setObjectName(_fromUtf8("copper_parm_box"))
        self.gridLayout = QtGui.QGridLayout(self.copper_parm_box)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidget = QtGui.QTableWidget(self.copper_parm_box)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableWidget.setToolTip(_fromUtf8(""))
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(95)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(33)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(22)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.copper_parm_box)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.panelizationButton = QtGui.QPushButton(Form)
        self.panelizationButton.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.panelizationButton.setFont(font)
        self.panelizationButton.setToolTip(_fromUtf8(""))
        self.panelizationButton.setStyleSheet(_fromUtf8("font: 12pt \"Agency FB\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;"))
        self.panelizationButton.setObjectName(_fromUtf8("panelizationButton"))
        self.horizontalLayout.addWidget(self.panelizationButton)
        self.applyButton = QtGui.QPushButton(Form)
        self.applyButton.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.applyButton.setFont(font)
        self.applyButton.setToolTip(_fromUtf8(""))
        self.applyButton.setStyleSheet(_fromUtf8("font: 12pt \"Agency FB\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;"))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.horizontalLayout.addWidget(self.applyButton)
        self.unlockUIButton = QtGui.QPushButton(Form)
        self.unlockUIButton.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.unlockUIButton.setFont(font)
        self.unlockUIButton.setToolTip(_fromUtf8(""))
        self.unlockUIButton.setStyleSheet(_fromUtf8("font: 12pt \"Times New Roman\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;"))
        self.unlockUIButton.setObjectName(_fromUtf8("unlockUIButton"))
        self.horizontalLayout.addWidget(self.unlockUIButton)
        spacerItem1 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.exitButton = QtGui.QPushButton(Form)
        self.exitButton.setMinimumSize(QtCore.QSize(100, 30))
        self.exitButton.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.exitButton.setFont(font)
        self.exitButton.setToolTip(_fromUtf8(""))
        self.exitButton.setStyleSheet(_fromUtf8("font: 12pt \"Agency FB\";\n"
"\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(137, 200, 255);\n"
"border-style:none;\n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:15px;\n"
"selection-background-color: rgb(170, 255, 0);"))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.horizontalLayout.addWidget(self.exitButton)
        spacerItem2 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.appVersion = QtGui.QLabel(Form)
        self.appVersion.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appVersion.sizePolicy().hasHeightForWidth())
        self.appVersion.setSizePolicy(sizePolicy)
        self.appVersion.setMinimumSize(QtCore.QSize(0, 25))
        self.appVersion.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.appVersion.setFont(font)
        self.appVersion.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.appVersion.setMargin(5)
        self.appVersion.setObjectName(_fromUtf8("appVersion"))
        self.verticalLayout.addWidget(self.appVersion)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.array_step, self.array_x_size)
        Form.setTabOrder(self.array_x_size, self.panel_x)
        Form.setTabOrder(self.panel_x, self.rout_x)
        Form.setTabOrder(self.rout_x, self.board_thick)
        Form.setTabOrder(self.board_thick, self.array_y_size)
        Form.setTabOrder(self.array_y_size, self.panel_y)
        Form.setTabOrder(self.panel_y, self.rout_y)
        Form.setTabOrder(self.rout_y, self.split_via)
        Form.setTabOrder(self.split_via, self.split_pth)
        Form.setTabOrder(self.split_pth, self.dry_hole)
        Form.setTabOrder(self.dry_hole, self.panel)
        Form.setTabOrder(self.panel, self.sh_site)
        Form.setTabOrder(self.sh_site, self.cycle_in_silk)
        Form.setTabOrder(self.cycle_in_silk, self.cycle_in_sm)
        Form.setTabOrder(self.cycle_in_sm, self.cycle_in_signal)
        Form.setTabOrder(self.cycle_in_signal, self.sel_jsz_no)
        Form.setTabOrder(self.sel_jsz_no, self.sel_jsz_yes)
        Form.setTabOrder(self.sel_jsz_yes, self.add_hj_panel_no)
        Form.setTabOrder(self.add_hj_panel_no, self.add_hj_panel_yes)
        Form.setTabOrder(self.add_hj_panel_yes, self.sel_finger_no)
        Form.setTabOrder(self.sel_finger_no, self.sel_finger_yes)
        Form.setTabOrder(self.sel_finger_yes, self.g_direction)
        Form.setTabOrder(self.g_direction, self.add_ld_symbol_no)
        Form.setTabOrder(self.add_ld_symbol_no, self.add_ld_symbol_yes)
        Form.setTabOrder(self.add_ld_symbol_yes, self.sel_vut_no)
        Form.setTabOrder(self.sel_vut_no, self.sel_vut_yes)
        Form.setTabOrder(self.sel_vut_yes, self.add_eagle_panel_no)
        Form.setTabOrder(self.add_eagle_panel_no, self.add_eagle_panel_yes)
        Form.setTabOrder(self.add_eagle_panel_yes, self.sel_mid_rout_short)
        Form.setTabOrder(self.sel_mid_rout_short, self.sel_mid_rout_long)
        Form.setTabOrder(self.sel_mid_rout_long, self.wei_xiang)
        Form.setTabOrder(self.wei_xiang, self.select_color_silk)
        Form.setTabOrder(self.select_color_silk, self.select_silk_times)
        Form.setTabOrder(self.select_silk_times, self.select_solder_times)
        Form.setTabOrder(self.select_solder_times, self.mao_pin_x)
        Form.setTabOrder(self.mao_pin_x, self.mao_pin_y)
        Form.setTabOrder(self.mao_pin_y, self.ape3000_base)
        Form.setTabOrder(self.ape3000_base, self.tableWidget_lamin)
        Form.setTabOrder(self.tableWidget_lamin, self.tableWidget)
        Form.setTabOrder(self.tableWidget, self.panelizationButton)
        Form.setTabOrder(self.panelizationButton, self.applyButton)
        Form.setTabOrder(self.applyButton, self.unlockUIButton)
        Form.setTabOrder(self.unlockUIButton, self.exitButton)
        Form.setTabOrder(self.exitButton, self.sel_socket_no)
        Form.setTabOrder(self.sel_socket_no, self.sel_socket_yes)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Panelization", None))
        self.topLabel.setText(_translate("Form", "胜宏科技HDI Panel板边", None))
        self.array_parm_box.setTitle(_translate("Form", "拼板信息（单位mm)", None))
        self.label_array_x_size.setText(_translate("Form", "单只尺寸X：", None))
        self.label_panel_x.setText(_translate("Form", "拼板尺寸X：", None))
        self.label_rout_x.setText(_translate("Form", "锣边后尺寸X：", None))
        self.label_board_thick.setText(_translate("Form", "板厚：", None))
        self.label_array_step.setText(_translate("Form", "单只名称：", None))
        self.label_split_pth.setText(_translate("Form", "切片PTH：", None))
        self.label_dry_hole.setText(_translate("Form", "角检测孔：", None))
        self.label_rout_y.setText(_translate("Form", "锣边后尺寸Y：", None))
        self.label_panel_y.setText(_translate("Form", "拼板尺寸Y：", None))
        self.label_split_via.setText(_translate("Form", "切片via：", None))
        self.label_array_y_size.setText(_translate("Form", "单只尺寸Y：", None))
        self.label_panel.setText(_translate("Form", "拼板名称：", None))
        self.panel.setText(_translate("Form", "panel", None))
        self.select_parm_box.setTitle(_translate("Form", "参数选择(单位mm)", None))
        self.label_sh_site.setText(_translate("Form", "选择工厂：", None))
        self.sh_site.setItemText(0, _translate("Form", "HDI一厂", None))
        self.sh_site.setItemText(1, _translate("Form", "HDI二厂", None))
        self.flow_content.setText(_translate("Form", "一次铜", None))
        self.label_sel_socket.setText(_translate("Form", "socket运行：", None))
        self.sel_socket_no.setText(_translate("Form", "否", None))
        self.sel_socket_yes.setText(_translate("Form", "是", None))
        self.label_cycle_in.setText(_translate("Form", "添加周期：", None))
        self.cycle_in_silk.setText(_translate("Form", "文字", None))
        self.cycle_in_sm.setText(_translate("Form", "绿油", None))
        self.cycle_in_signal.setText(_translate("Form", "线路", None))
        self.label_add_ld_symbol.setText(_translate("Form", "镭雕制程：", None))
        self.add_ld_symbol_no.setText(_translate("Form", "否", None))
        self.add_ld_symbol_yes.setText(_translate("Form", "是", None))
        self.label_sel_vut.setText(_translate("Form", "大板V-CUT：", None))
        self.sel_vut_no.setText(_translate("Form", "否", None))
        self.sel_vut_yes.setText(_translate("Form", "是", None))
        self.label_add_eagle_panel.setText(_translate("Form", "LED板：", None))
        self.add_eagle_panel_no.setText(_translate("Form", "否", None))
        self.add_eagle_panel_yes.setText(_translate("Form", "是", None))
        self.sel_mid_rout_short.setText(_translate("Form", "短边", None))
        self.sel_mid_rout_long.setText(_translate("Form", "长边", None))
        self.label_wei_xiang.setText(_translate("Form", "纬向：", None))
        self.wei_xiang.setItemText(0, _translate("Form", "未选中", None))
        self.wei_xiang.setItemText(1, _translate("Form", "纬向X", None))
        self.wei_xiang.setItemText(2, _translate("Form", "纬向Y", None))
        self.label_select_color_silk.setText(_translate("Form", "文字颜色：", None))
        self.select_color_silk.setItemText(0, _translate("Form", "白色", None))
        self.select_color_silk.setItemText(1, _translate("Form", "黄色", None))
        self.select_color_silk.setItemText(2, _translate("Form", "黑色", None))
        self.select_color_silk.setItemText(3, _translate("Form", "亮黑色", None))
        self.select_color_silk.setItemText(4, _translate("Form", "红色", None))
        self.select_color_silk.setItemText(5, _translate("Form", "亮红色", None))
        self.select_color_silk.setItemText(6, _translate("Form", "雾红色", None))
        self.select_color_silk.setItemText(7, _translate("Form", "灰色", None))
        self.select_color_silk.setItemText(8, _translate("Form", "深灰色", None))
        self.select_color_silk.setItemText(9, _translate("Form", "冷灰色", None))
        self.select_color_silk.setItemText(10, _translate("Form", "橘色", None))
        self.select_color_silk.setItemText(11, _translate("Form", "蓝绿色", None))
        self.select_color_silk.setItemText(12, _translate("Form", "绿色", None))
        self.select_color_silk.setItemText(13, _translate("Form", "蓝色", None))
        self.select_color_silk.setItemText(14, _translate("Form", "粉色", None))
        self.select_color_silk.setItemText(15, _translate("Form", "两面不同", None))
        self.select_color_silk.setItemText(16, _translate("Form", "见流程栏备注", None))        
        self.label_select_silk_times.setText(_translate("Form", "文字次数", None))
        self.select_silk_times.setItemText(0, _translate("Form", "无", None))
        self.select_silk_times.setItemText(1, _translate("Form", "一次", None))
        self.select_silk_times.setItemText(2, _translate("Form", "二次", None))
        self.select_silk_times.setItemText(3, _translate("Form", "三次", None))
        self.label_select_solder_times.setText(_translate("Form", "防焊次数", None))
        self.select_solder_times.setItemText(0, _translate("Form", "无", None))
        self.select_solder_times.setItemText(1, _translate("Form", "一次", None))
        self.select_solder_times.setItemText(2, _translate("Form", "二次", None))
        self.select_solder_times.setItemText(3, _translate("Form", "三次", None))
        self.label_sel_mid_rout.setText(_translate("Form", "一厂化金保留铜皮：", None))
        self.label_sel_finger.setText(_translate("Form", "手指选化：", None))
        self.label_if_jsz.setText(_translate("Form", "是否金手指：", None))
        self.sel_jsz_no.setText(_translate("Form", "否", None))
        self.sel_jsz_yes.setText(_translate("Form", "是", None))
        self.label_add_hj_panel.setText(_translate("Form", "化金板：", None))
        self.add_hj_panel_no.setText(_translate("Form", "否", None))
        self.add_hj_panel_yes.setText(_translate("Form", "是", None))
        self.sel_finger_no.setText(_translate("Form", "否", None))
        self.sel_finger_yes.setText(_translate("Form", "是", None))
        self.label_g_direction.setText(_translate("Form", "板内手指方向：", None))
        self.g_direction.setItemText(0, _translate("Form", "请选择", None))
        self.g_direction.setItemText(1, _translate("Form", "X方向", None))
        self.g_direction.setItemText(2, _translate("Form", "Y方向", None))
        self.g_direction.setItemText(3, _translate("Form", "XY均有", None))
        self.mao_ding_parm_box.setTitle(_translate("Form", "参数选择(单位inch)", None))
        self.ape3000_base.setItemText(0, _translate("Form", "0.5inch", None))
        self.ape3000_base.setItemText(1, _translate("Form", "0.25inch", None))
        self.label_ape3000_base.setText(_translate("Form", "PE3000进制：", None))
        self.label_mao_pin_y.setText(_translate("Form", "铆钉Y：", None))
        self.label_mao_pin_x.setText(_translate("Form", "铆钉X：", None))
        self.pin_lam_mode.setText(_translate("Form", "pin_lam模式", None))
        self.lamin_parm_box.setTitle(_translate("Form", "压合参数列表", None))
        item = self.tableWidget_lamin.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.tableWidget_lamin.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.tableWidget_lamin.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(0)
        item.setText(_translate("Form", "压合次数", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(1)
        item.setText(_translate("Form", "起始层", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(2)
        item.setText(_translate("Form", "终止层", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(3)
        item.setText(_translate("Form", "锣边X(\")", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(4)
        item.setText(_translate("Form", "锣边Y(\")", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(5)
        item.setText(_translate("Form", "烧靶(0=否)", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(6)
        item.setText(_translate("Form", "4靶X1", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(7)
        item.setText(_translate("Form", "4靶X2", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(8)
        item.setText(_translate("Form", "4靶Y1", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(9)
        item.setText(_translate("Form", "4靶Y2", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(10)
        item.setText(_translate("Form", "箭靶X", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(11)
        item.setText(_translate("Form", "箭靶Y", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(12)
        item.setText(_translate("Form", "线路靶Y1", None))
        item = self.tableWidget_lamin.horizontalHeaderItem(13)
        item.setText(_translate("Form", "线路靶Y2", None))
        __sortingEnabled = self.tableWidget_lamin.isSortingEnabled()
        self.tableWidget_lamin.setSortingEnabled(False)
        self.tableWidget_lamin.setSortingEnabled(__sortingEnabled)
        self.copper_parm_box.setTitle(_translate("Form", "铺铜参数列表", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "层名", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "铜厚", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Side", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "极性", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "板边填铜方式", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "压合级别", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "干膜尺寸", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "l2", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "l3", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "l4", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "l5", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.panelizationButton.setText(_translate("Form", "排版", None))
        self.applyButton.setText(_translate("Form", "跑板边", None))
        self.unlockUIButton.setText(_translate("Form", "解锁界面锁定项", None))
        self.exitButton.setText(_translate("Form", "退出", None))
        self.appVersion.setText(_translate("Form", "版权所有：胜宏科技 作者：Michael 日期：2020.11.10 版本：V1.00", None))

import apprcc_rc
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
